// source: inbox_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.core.api.proto.InboxSegmentUpdate');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.core.api.proto.InboxSegmentUpdate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.core.api.proto.InboxSegmentUpdate.repeatedFields_, null);
};
goog.inherits(proto.core.api.proto.InboxSegmentUpdate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.core.api.proto.InboxSegmentUpdate.displayName = 'proto.core.api.proto.InboxSegmentUpdate';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.core.api.proto.InboxSegmentUpdate.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.toObject = function(opt_includeInstance) {
  return proto.core.api.proto.InboxSegmentUpdate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.core.api.proto.InboxSegmentUpdate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.core.api.proto.InboxSegmentUpdate.toObject = function(includeInstance, msg) {
  var f, obj = {
    inboxSegmentId: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    parentConcernId: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    title: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    startIndex: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    totalAvailableConcerns: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
    concernIdToInsertList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f,
    asyncFetchInProgress: (f = jspb.Message.getBooleanField(msg, 7)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.core.api.proto.InboxSegmentUpdate}
 */
proto.core.api.proto.InboxSegmentUpdate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.core.api.proto.InboxSegmentUpdate;
  return proto.core.api.proto.InboxSegmentUpdate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.core.api.proto.InboxSegmentUpdate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.core.api.proto.InboxSegmentUpdate}
 */
proto.core.api.proto.InboxSegmentUpdate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setInboxSegmentId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setParentConcernId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setStartIndex(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTotalAvailableConcerns(value);
      break;
    case 6:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedUint64() : [reader.readUint64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addConcernIdToInsert(values[i]);
      }
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAsyncFetchInProgress(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.core.api.proto.InboxSegmentUpdate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.core.api.proto.InboxSegmentUpdate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.core.api.proto.InboxSegmentUpdate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getConcernIdToInsertList();
  if (f.length > 0) {
    writer.writeRepeatedUint64(
      6,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeBool(
      7,
      f
    );
  }
};


/**
 * optional uint64 inbox_segment_id = 1;
 * @return {number}
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.getInboxSegmentId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.core.api.proto.InboxSegmentUpdate} returns this
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.setInboxSegmentId = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.core.api.proto.InboxSegmentUpdate} returns this
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.clearInboxSegmentId = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.hasInboxSegmentId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint64 parent_concern_id = 2;
 * @return {number}
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.getParentConcernId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.core.api.proto.InboxSegmentUpdate} returns this
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.setParentConcernId = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.core.api.proto.InboxSegmentUpdate} returns this
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.clearParentConcernId = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.hasParentConcernId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string title = 3;
 * @return {string}
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.core.api.proto.InboxSegmentUpdate} returns this
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.setTitle = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.core.api.proto.InboxSegmentUpdate} returns this
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.clearTitle = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.hasTitle = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional uint32 start_index = 4;
 * @return {number}
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.getStartIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.core.api.proto.InboxSegmentUpdate} returns this
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.setStartIndex = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.core.api.proto.InboxSegmentUpdate} returns this
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.clearStartIndex = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.hasStartIndex = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional uint32 total_available_concerns = 5;
 * @return {number}
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.getTotalAvailableConcerns = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.core.api.proto.InboxSegmentUpdate} returns this
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.setTotalAvailableConcerns = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.core.api.proto.InboxSegmentUpdate} returns this
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.clearTotalAvailableConcerns = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.hasTotalAvailableConcerns = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * repeated uint64 concern_id_to_insert = 6;
 * @return {!Array<number>}
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.getConcernIdToInsertList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.core.api.proto.InboxSegmentUpdate} returns this
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.setConcernIdToInsertList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.core.api.proto.InboxSegmentUpdate} returns this
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.addConcernIdToInsert = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.core.api.proto.InboxSegmentUpdate} returns this
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.clearConcernIdToInsertList = function() {
  return this.setConcernIdToInsertList([]);
};


/**
 * optional bool async_fetch_in_progress = 7;
 * @return {boolean}
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.getAsyncFetchInProgress = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.core.api.proto.InboxSegmentUpdate} returns this
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.setAsyncFetchInProgress = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.core.api.proto.InboxSegmentUpdate} returns this
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.clearAsyncFetchInProgress = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.core.api.proto.InboxSegmentUpdate.prototype.hasAsyncFetchInProgress = function() {
  return jspb.Message.getField(this, 7) != null;
};


