// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: concern_service.proto

package core.api.proto;

public final class ConcernService {
  private ConcernService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code core.api.proto.GetConcernStatus}
   */
  public enum GetConcernStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GET_CONCERN_STATUS_UNKNOWN = 0;</code>
     */
    GET_CONCERN_STATUS_UNKNOWN(0),
    /**
     * <code>GET_CONCERN_STATUS_OK = 1;</code>
     */
    GET_CONCERN_STATUS_OK(1),
    /**
     * <code>GET_CONCERN_STATUS_CONCERN_NOT_FOUND = 2;</code>
     */
    GET_CONCERN_STATUS_CONCERN_NOT_FOUND(2),
    ;

    /**
     * <code>GET_CONCERN_STATUS_UNKNOWN = 0;</code>
     */
    public static final int GET_CONCERN_STATUS_UNKNOWN_VALUE = 0;
    /**
     * <code>GET_CONCERN_STATUS_OK = 1;</code>
     */
    public static final int GET_CONCERN_STATUS_OK_VALUE = 1;
    /**
     * <code>GET_CONCERN_STATUS_CONCERN_NOT_FOUND = 2;</code>
     */
    public static final int GET_CONCERN_STATUS_CONCERN_NOT_FOUND_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static GetConcernStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static GetConcernStatus forNumber(int value) {
      switch (value) {
        case 0: return GET_CONCERN_STATUS_UNKNOWN;
        case 1: return GET_CONCERN_STATUS_OK;
        case 2: return GET_CONCERN_STATUS_CONCERN_NOT_FOUND;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GetConcernStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GetConcernStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GetConcernStatus>() {
            public GetConcernStatus findValueByNumber(int number) {
              return GetConcernStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return core.api.proto.ConcernService.getDescriptor().getEnumTypes().get(0);
    }

    private static final GetConcernStatus[] VALUES = values();

    public static GetConcernStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GetConcernStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:core.api.proto.GetConcernStatus)
  }

  public interface RenderableConcernOrBuilder extends
      // @@protoc_insertion_point(interface_extends:core.api.proto.RenderableConcern)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 concern_id = 1;</code>
     * @return Whether the concernId field is set.
     */
    boolean hasConcernId();
    /**
     * <code>optional uint64 concern_id = 1;</code>
     * @return The concernId.
     */
    long getConcernId();

    /**
     * <code>optional string title = 2;</code>
     * @return Whether the title field is set.
     */
    boolean hasTitle();
    /**
     * <code>optional string title = 2;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>optional string preview = 3;</code>
     * @return Whether the preview field is set.
     */
    boolean hasPreview();
    /**
     * <code>optional string preview = 3;</code>
     * @return The preview.
     */
    java.lang.String getPreview();
    /**
     * <code>optional string preview = 3;</code>
     * @return The bytes for preview.
     */
    com.google.protobuf.ByteString
        getPreviewBytes();

    /**
     * <code>optional string url = 4;</code>
     * @return Whether the url field is set.
     */
    boolean hasUrl();
    /**
     * <code>optional string url = 4;</code>
     * @return The url.
     */
    java.lang.String getUrl();
    /**
     * <code>optional string url = 4;</code>
     * @return The bytes for url.
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>optional .core.api.proto.RenderableSource source = 5;</code>
     * @return Whether the source field is set.
     */
    boolean hasSource();
    /**
     * <code>optional .core.api.proto.RenderableSource source = 5;</code>
     * @return The source.
     */
    core.api.proto.Sources.RenderableSource getSource();
    /**
     * <code>optional .core.api.proto.RenderableSource source = 5;</code>
     */
    core.api.proto.Sources.RenderableSourceOrBuilder getSourceOrBuilder();
  }
  /**
   * Protobuf type {@code core.api.proto.RenderableConcern}
   */
  public static final class RenderableConcern extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:core.api.proto.RenderableConcern)
      RenderableConcernOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RenderableConcern.newBuilder() to construct.
    private RenderableConcern(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RenderableConcern() {
      title_ = "";
      preview_ = "";
      url_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RenderableConcern();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return core.api.proto.ConcernService.internal_static_core_api_proto_RenderableConcern_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return core.api.proto.ConcernService.internal_static_core_api_proto_RenderableConcern_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              core.api.proto.ConcernService.RenderableConcern.class, core.api.proto.ConcernService.RenderableConcern.Builder.class);
    }

    private int bitField0_;
    public static final int CONCERN_ID_FIELD_NUMBER = 1;
    private long concernId_ = 0L;
    /**
     * <code>optional uint64 concern_id = 1;</code>
     * @return Whether the concernId field is set.
     */
    @java.lang.Override
    public boolean hasConcernId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 concern_id = 1;</code>
     * @return The concernId.
     */
    @java.lang.Override
    public long getConcernId() {
      return concernId_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object title_ = "";
    /**
     * <code>optional string title = 2;</code>
     * @return Whether the title field is set.
     */
    @java.lang.Override
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PREVIEW_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object preview_ = "";
    /**
     * <code>optional string preview = 3;</code>
     * @return Whether the preview field is set.
     */
    @java.lang.Override
    public boolean hasPreview() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string preview = 3;</code>
     * @return The preview.
     */
    @java.lang.Override
    public java.lang.String getPreview() {
      java.lang.Object ref = preview_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          preview_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string preview = 3;</code>
     * @return The bytes for preview.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPreviewBytes() {
      java.lang.Object ref = preview_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        preview_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URL_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object url_ = "";
    /**
     * <code>optional string url = 4;</code>
     * @return Whether the url field is set.
     */
    @java.lang.Override
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string url = 4;</code>
     * @return The url.
     */
    @java.lang.Override
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          url_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string url = 4;</code>
     * @return The bytes for url.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCE_FIELD_NUMBER = 5;
    private core.api.proto.Sources.RenderableSource source_;
    /**
     * <code>optional .core.api.proto.RenderableSource source = 5;</code>
     * @return Whether the source field is set.
     */
    @java.lang.Override
    public boolean hasSource() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .core.api.proto.RenderableSource source = 5;</code>
     * @return The source.
     */
    @java.lang.Override
    public core.api.proto.Sources.RenderableSource getSource() {
      return source_ == null ? core.api.proto.Sources.RenderableSource.getDefaultInstance() : source_;
    }
    /**
     * <code>optional .core.api.proto.RenderableSource source = 5;</code>
     */
    @java.lang.Override
    public core.api.proto.Sources.RenderableSourceOrBuilder getSourceOrBuilder() {
      return source_ == null ? core.api.proto.Sources.RenderableSource.getDefaultInstance() : source_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, concernId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, preview_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, url_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeMessage(5, getSource());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, concernId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, preview_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, url_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getSource());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof core.api.proto.ConcernService.RenderableConcern)) {
        return super.equals(obj);
      }
      core.api.proto.ConcernService.RenderableConcern other = (core.api.proto.ConcernService.RenderableConcern) obj;

      if (hasConcernId() != other.hasConcernId()) return false;
      if (hasConcernId()) {
        if (getConcernId()
            != other.getConcernId()) return false;
      }
      if (hasTitle() != other.hasTitle()) return false;
      if (hasTitle()) {
        if (!getTitle()
            .equals(other.getTitle())) return false;
      }
      if (hasPreview() != other.hasPreview()) return false;
      if (hasPreview()) {
        if (!getPreview()
            .equals(other.getPreview())) return false;
      }
      if (hasUrl() != other.hasUrl()) return false;
      if (hasUrl()) {
        if (!getUrl()
            .equals(other.getUrl())) return false;
      }
      if (hasSource() != other.hasSource()) return false;
      if (hasSource()) {
        if (!getSource()
            .equals(other.getSource())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasConcernId()) {
        hash = (37 * hash) + CONCERN_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getConcernId());
      }
      if (hasTitle()) {
        hash = (37 * hash) + TITLE_FIELD_NUMBER;
        hash = (53 * hash) + getTitle().hashCode();
      }
      if (hasPreview()) {
        hash = (37 * hash) + PREVIEW_FIELD_NUMBER;
        hash = (53 * hash) + getPreview().hashCode();
      }
      if (hasUrl()) {
        hash = (37 * hash) + URL_FIELD_NUMBER;
        hash = (53 * hash) + getUrl().hashCode();
      }
      if (hasSource()) {
        hash = (37 * hash) + SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getSource().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static core.api.proto.ConcernService.RenderableConcern parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.ConcernService.RenderableConcern parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.ConcernService.RenderableConcern parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.ConcernService.RenderableConcern parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.ConcernService.RenderableConcern parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.ConcernService.RenderableConcern parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.ConcernService.RenderableConcern parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static core.api.proto.ConcernService.RenderableConcern parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static core.api.proto.ConcernService.RenderableConcern parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static core.api.proto.ConcernService.RenderableConcern parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static core.api.proto.ConcernService.RenderableConcern parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static core.api.proto.ConcernService.RenderableConcern parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(core.api.proto.ConcernService.RenderableConcern prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code core.api.proto.RenderableConcern}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:core.api.proto.RenderableConcern)
        core.api.proto.ConcernService.RenderableConcernOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return core.api.proto.ConcernService.internal_static_core_api_proto_RenderableConcern_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return core.api.proto.ConcernService.internal_static_core_api_proto_RenderableConcern_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                core.api.proto.ConcernService.RenderableConcern.class, core.api.proto.ConcernService.RenderableConcern.Builder.class);
      }

      // Construct using core.api.proto.ConcernService.RenderableConcern.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSourceFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        concernId_ = 0L;
        title_ = "";
        preview_ = "";
        url_ = "";
        source_ = null;
        if (sourceBuilder_ != null) {
          sourceBuilder_.dispose();
          sourceBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return core.api.proto.ConcernService.internal_static_core_api_proto_RenderableConcern_descriptor;
      }

      @java.lang.Override
      public core.api.proto.ConcernService.RenderableConcern getDefaultInstanceForType() {
        return core.api.proto.ConcernService.RenderableConcern.getDefaultInstance();
      }

      @java.lang.Override
      public core.api.proto.ConcernService.RenderableConcern build() {
        core.api.proto.ConcernService.RenderableConcern result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public core.api.proto.ConcernService.RenderableConcern buildPartial() {
        core.api.proto.ConcernService.RenderableConcern result = new core.api.proto.ConcernService.RenderableConcern(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(core.api.proto.ConcernService.RenderableConcern result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.concernId_ = concernId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.title_ = title_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.preview_ = preview_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.url_ = url_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.source_ = sourceBuilder_ == null
              ? source_
              : sourceBuilder_.build();
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof core.api.proto.ConcernService.RenderableConcern) {
          return mergeFrom((core.api.proto.ConcernService.RenderableConcern)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(core.api.proto.ConcernService.RenderableConcern other) {
        if (other == core.api.proto.ConcernService.RenderableConcern.getDefaultInstance()) return this;
        if (other.hasConcernId()) {
          setConcernId(other.getConcernId());
        }
        if (other.hasTitle()) {
          title_ = other.title_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasPreview()) {
          preview_ = other.preview_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasUrl()) {
          url_ = other.url_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasSource()) {
          mergeSource(other.getSource());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                concernId_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                title_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                preview_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                url_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getSourceFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long concernId_ ;
      /**
       * <code>optional uint64 concern_id = 1;</code>
       * @return Whether the concernId field is set.
       */
      @java.lang.Override
      public boolean hasConcernId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint64 concern_id = 1;</code>
       * @return The concernId.
       */
      @java.lang.Override
      public long getConcernId() {
        return concernId_;
      }
      /**
       * <code>optional uint64 concern_id = 1;</code>
       * @param value The concernId to set.
       * @return This builder for chaining.
       */
      public Builder setConcernId(long value) {

        concernId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 concern_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearConcernId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        concernId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>optional string title = 2;</code>
       * @return Whether the title field is set.
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string title = 2;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        title_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        title_ = getDefaultInstance().getTitle();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        title_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object preview_ = "";
      /**
       * <code>optional string preview = 3;</code>
       * @return Whether the preview field is set.
       */
      public boolean hasPreview() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string preview = 3;</code>
       * @return The preview.
       */
      public java.lang.String getPreview() {
        java.lang.Object ref = preview_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            preview_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string preview = 3;</code>
       * @return The bytes for preview.
       */
      public com.google.protobuf.ByteString
          getPreviewBytes() {
        java.lang.Object ref = preview_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          preview_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string preview = 3;</code>
       * @param value The preview to set.
       * @return This builder for chaining.
       */
      public Builder setPreview(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        preview_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string preview = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPreview() {
        preview_ = getDefaultInstance().getPreview();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string preview = 3;</code>
       * @param value The bytes for preview to set.
       * @return This builder for chaining.
       */
      public Builder setPreviewBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        preview_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <code>optional string url = 4;</code>
       * @return Whether the url field is set.
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string url = 4;</code>
       * @return The url.
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            url_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string url = 4;</code>
       * @return The bytes for url.
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string url = 4;</code>
       * @param value The url to set.
       * @return This builder for chaining.
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        url_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional string url = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUrl() {
        url_ = getDefaultInstance().getUrl();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>optional string url = 4;</code>
       * @param value The bytes for url to set.
       * @return This builder for chaining.
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        url_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private core.api.proto.Sources.RenderableSource source_;
      private com.google.protobuf.SingleFieldBuilderV3<
          core.api.proto.Sources.RenderableSource, core.api.proto.Sources.RenderableSource.Builder, core.api.proto.Sources.RenderableSourceOrBuilder> sourceBuilder_;
      /**
       * <code>optional .core.api.proto.RenderableSource source = 5;</code>
       * @return Whether the source field is set.
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional .core.api.proto.RenderableSource source = 5;</code>
       * @return The source.
       */
      public core.api.proto.Sources.RenderableSource getSource() {
        if (sourceBuilder_ == null) {
          return source_ == null ? core.api.proto.Sources.RenderableSource.getDefaultInstance() : source_;
        } else {
          return sourceBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .core.api.proto.RenderableSource source = 5;</code>
       */
      public Builder setSource(core.api.proto.Sources.RenderableSource value) {
        if (sourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          source_ = value;
        } else {
          sourceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional .core.api.proto.RenderableSource source = 5;</code>
       */
      public Builder setSource(
          core.api.proto.Sources.RenderableSource.Builder builderForValue) {
        if (sourceBuilder_ == null) {
          source_ = builderForValue.build();
        } else {
          sourceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional .core.api.proto.RenderableSource source = 5;</code>
       */
      public Builder mergeSource(core.api.proto.Sources.RenderableSource value) {
        if (sourceBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            source_ != null &&
            source_ != core.api.proto.Sources.RenderableSource.getDefaultInstance()) {
            getSourceBuilder().mergeFrom(value);
          } else {
            source_ = value;
          }
        } else {
          sourceBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional .core.api.proto.RenderableSource source = 5;</code>
       */
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000010);
        source_ = null;
        if (sourceBuilder_ != null) {
          sourceBuilder_.dispose();
          sourceBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .core.api.proto.RenderableSource source = 5;</code>
       */
      public core.api.proto.Sources.RenderableSource.Builder getSourceBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getSourceFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .core.api.proto.RenderableSource source = 5;</code>
       */
      public core.api.proto.Sources.RenderableSourceOrBuilder getSourceOrBuilder() {
        if (sourceBuilder_ != null) {
          return sourceBuilder_.getMessageOrBuilder();
        } else {
          return source_ == null ?
              core.api.proto.Sources.RenderableSource.getDefaultInstance() : source_;
        }
      }
      /**
       * <code>optional .core.api.proto.RenderableSource source = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          core.api.proto.Sources.RenderableSource, core.api.proto.Sources.RenderableSource.Builder, core.api.proto.Sources.RenderableSourceOrBuilder> 
          getSourceFieldBuilder() {
        if (sourceBuilder_ == null) {
          sourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              core.api.proto.Sources.RenderableSource, core.api.proto.Sources.RenderableSource.Builder, core.api.proto.Sources.RenderableSourceOrBuilder>(
                  getSource(),
                  getParentForChildren(),
                  isClean());
          source_ = null;
        }
        return sourceBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:core.api.proto.RenderableConcern)
    }

    // @@protoc_insertion_point(class_scope:core.api.proto.RenderableConcern)
    private static final core.api.proto.ConcernService.RenderableConcern DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new core.api.proto.ConcernService.RenderableConcern();
    }

    public static core.api.proto.ConcernService.RenderableConcern getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RenderableConcern>
        PARSER = new com.google.protobuf.AbstractParser<RenderableConcern>() {
      @java.lang.Override
      public RenderableConcern parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RenderableConcern> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RenderableConcern> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public core.api.proto.ConcernService.RenderableConcern getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetConcernRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:core.api.proto.GetConcernRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 concern_id = 1;</code>
     * @return Whether the concernId field is set.
     */
    boolean hasConcernId();
    /**
     * <code>optional uint64 concern_id = 1;</code>
     * @return The concernId.
     */
    long getConcernId();
  }
  /**
   * Protobuf type {@code core.api.proto.GetConcernRequest}
   */
  public static final class GetConcernRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:core.api.proto.GetConcernRequest)
      GetConcernRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetConcernRequest.newBuilder() to construct.
    private GetConcernRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetConcernRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetConcernRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return core.api.proto.ConcernService.internal_static_core_api_proto_GetConcernRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return core.api.proto.ConcernService.internal_static_core_api_proto_GetConcernRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              core.api.proto.ConcernService.GetConcernRequest.class, core.api.proto.ConcernService.GetConcernRequest.Builder.class);
    }

    private int bitField0_;
    public static final int CONCERN_ID_FIELD_NUMBER = 1;
    private long concernId_ = 0L;
    /**
     * <code>optional uint64 concern_id = 1;</code>
     * @return Whether the concernId field is set.
     */
    @java.lang.Override
    public boolean hasConcernId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 concern_id = 1;</code>
     * @return The concernId.
     */
    @java.lang.Override
    public long getConcernId() {
      return concernId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, concernId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, concernId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof core.api.proto.ConcernService.GetConcernRequest)) {
        return super.equals(obj);
      }
      core.api.proto.ConcernService.GetConcernRequest other = (core.api.proto.ConcernService.GetConcernRequest) obj;

      if (hasConcernId() != other.hasConcernId()) return false;
      if (hasConcernId()) {
        if (getConcernId()
            != other.getConcernId()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasConcernId()) {
        hash = (37 * hash) + CONCERN_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getConcernId());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static core.api.proto.ConcernService.GetConcernRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.ConcernService.GetConcernRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.ConcernService.GetConcernRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.ConcernService.GetConcernRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.ConcernService.GetConcernRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.ConcernService.GetConcernRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.ConcernService.GetConcernRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static core.api.proto.ConcernService.GetConcernRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static core.api.proto.ConcernService.GetConcernRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static core.api.proto.ConcernService.GetConcernRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static core.api.proto.ConcernService.GetConcernRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static core.api.proto.ConcernService.GetConcernRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(core.api.proto.ConcernService.GetConcernRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code core.api.proto.GetConcernRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:core.api.proto.GetConcernRequest)
        core.api.proto.ConcernService.GetConcernRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return core.api.proto.ConcernService.internal_static_core_api_proto_GetConcernRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return core.api.proto.ConcernService.internal_static_core_api_proto_GetConcernRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                core.api.proto.ConcernService.GetConcernRequest.class, core.api.proto.ConcernService.GetConcernRequest.Builder.class);
      }

      // Construct using core.api.proto.ConcernService.GetConcernRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        concernId_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return core.api.proto.ConcernService.internal_static_core_api_proto_GetConcernRequest_descriptor;
      }

      @java.lang.Override
      public core.api.proto.ConcernService.GetConcernRequest getDefaultInstanceForType() {
        return core.api.proto.ConcernService.GetConcernRequest.getDefaultInstance();
      }

      @java.lang.Override
      public core.api.proto.ConcernService.GetConcernRequest build() {
        core.api.proto.ConcernService.GetConcernRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public core.api.proto.ConcernService.GetConcernRequest buildPartial() {
        core.api.proto.ConcernService.GetConcernRequest result = new core.api.proto.ConcernService.GetConcernRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(core.api.proto.ConcernService.GetConcernRequest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.concernId_ = concernId_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof core.api.proto.ConcernService.GetConcernRequest) {
          return mergeFrom((core.api.proto.ConcernService.GetConcernRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(core.api.proto.ConcernService.GetConcernRequest other) {
        if (other == core.api.proto.ConcernService.GetConcernRequest.getDefaultInstance()) return this;
        if (other.hasConcernId()) {
          setConcernId(other.getConcernId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                concernId_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long concernId_ ;
      /**
       * <code>optional uint64 concern_id = 1;</code>
       * @return Whether the concernId field is set.
       */
      @java.lang.Override
      public boolean hasConcernId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint64 concern_id = 1;</code>
       * @return The concernId.
       */
      @java.lang.Override
      public long getConcernId() {
        return concernId_;
      }
      /**
       * <code>optional uint64 concern_id = 1;</code>
       * @param value The concernId to set.
       * @return This builder for chaining.
       */
      public Builder setConcernId(long value) {

        concernId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 concern_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearConcernId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        concernId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:core.api.proto.GetConcernRequest)
    }

    // @@protoc_insertion_point(class_scope:core.api.proto.GetConcernRequest)
    private static final core.api.proto.ConcernService.GetConcernRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new core.api.proto.ConcernService.GetConcernRequest();
    }

    public static core.api.proto.ConcernService.GetConcernRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GetConcernRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetConcernRequest>() {
      @java.lang.Override
      public GetConcernRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetConcernRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetConcernRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public core.api.proto.ConcernService.GetConcernRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetConcernResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:core.api.proto.GetConcernResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .core.api.proto.RenderableConcern concern = 1;</code>
     * @return Whether the concern field is set.
     */
    boolean hasConcern();
    /**
     * <code>optional .core.api.proto.RenderableConcern concern = 1;</code>
     * @return The concern.
     */
    core.api.proto.ConcernService.RenderableConcern getConcern();
    /**
     * <code>optional .core.api.proto.RenderableConcern concern = 1;</code>
     */
    core.api.proto.ConcernService.RenderableConcernOrBuilder getConcernOrBuilder();

    /**
     * <code>optional .core.api.proto.GetConcernStatus status = 2;</code>
     * @return Whether the status field is set.
     */
    boolean hasStatus();
    /**
     * <code>optional .core.api.proto.GetConcernStatus status = 2;</code>
     * @return The status.
     */
    core.api.proto.ConcernService.GetConcernStatus getStatus();
  }
  /**
   * Protobuf type {@code core.api.proto.GetConcernResponse}
   */
  public static final class GetConcernResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:core.api.proto.GetConcernResponse)
      GetConcernResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetConcernResponse.newBuilder() to construct.
    private GetConcernResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetConcernResponse() {
      status_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetConcernResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return core.api.proto.ConcernService.internal_static_core_api_proto_GetConcernResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return core.api.proto.ConcernService.internal_static_core_api_proto_GetConcernResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              core.api.proto.ConcernService.GetConcernResponse.class, core.api.proto.ConcernService.GetConcernResponse.Builder.class);
    }

    private int bitField0_;
    public static final int CONCERN_FIELD_NUMBER = 1;
    private core.api.proto.ConcernService.RenderableConcern concern_;
    /**
     * <code>optional .core.api.proto.RenderableConcern concern = 1;</code>
     * @return Whether the concern field is set.
     */
    @java.lang.Override
    public boolean hasConcern() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .core.api.proto.RenderableConcern concern = 1;</code>
     * @return The concern.
     */
    @java.lang.Override
    public core.api.proto.ConcernService.RenderableConcern getConcern() {
      return concern_ == null ? core.api.proto.ConcernService.RenderableConcern.getDefaultInstance() : concern_;
    }
    /**
     * <code>optional .core.api.proto.RenderableConcern concern = 1;</code>
     */
    @java.lang.Override
    public core.api.proto.ConcernService.RenderableConcernOrBuilder getConcernOrBuilder() {
      return concern_ == null ? core.api.proto.ConcernService.RenderableConcern.getDefaultInstance() : concern_;
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_ = 0;
    /**
     * <code>optional .core.api.proto.GetConcernStatus status = 2;</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .core.api.proto.GetConcernStatus status = 2;</code>
     * @return The status.
     */
    @java.lang.Override public core.api.proto.ConcernService.GetConcernStatus getStatus() {
      core.api.proto.ConcernService.GetConcernStatus result = core.api.proto.ConcernService.GetConcernStatus.forNumber(status_);
      return result == null ? core.api.proto.ConcernService.GetConcernStatus.GET_CONCERN_STATUS_UNKNOWN : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getConcern());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, status_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getConcern());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof core.api.proto.ConcernService.GetConcernResponse)) {
        return super.equals(obj);
      }
      core.api.proto.ConcernService.GetConcernResponse other = (core.api.proto.ConcernService.GetConcernResponse) obj;

      if (hasConcern() != other.hasConcern()) return false;
      if (hasConcern()) {
        if (!getConcern()
            .equals(other.getConcern())) return false;
      }
      if (hasStatus() != other.hasStatus()) return false;
      if (hasStatus()) {
        if (status_ != other.status_) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasConcern()) {
        hash = (37 * hash) + CONCERN_FIELD_NUMBER;
        hash = (53 * hash) + getConcern().hashCode();
      }
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + status_;
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static core.api.proto.ConcernService.GetConcernResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.ConcernService.GetConcernResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.ConcernService.GetConcernResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.ConcernService.GetConcernResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.ConcernService.GetConcernResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.ConcernService.GetConcernResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.ConcernService.GetConcernResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static core.api.proto.ConcernService.GetConcernResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static core.api.proto.ConcernService.GetConcernResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static core.api.proto.ConcernService.GetConcernResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static core.api.proto.ConcernService.GetConcernResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static core.api.proto.ConcernService.GetConcernResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(core.api.proto.ConcernService.GetConcernResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code core.api.proto.GetConcernResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:core.api.proto.GetConcernResponse)
        core.api.proto.ConcernService.GetConcernResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return core.api.proto.ConcernService.internal_static_core_api_proto_GetConcernResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return core.api.proto.ConcernService.internal_static_core_api_proto_GetConcernResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                core.api.proto.ConcernService.GetConcernResponse.class, core.api.proto.ConcernService.GetConcernResponse.Builder.class);
      }

      // Construct using core.api.proto.ConcernService.GetConcernResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getConcernFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        concern_ = null;
        if (concernBuilder_ != null) {
          concernBuilder_.dispose();
          concernBuilder_ = null;
        }
        status_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return core.api.proto.ConcernService.internal_static_core_api_proto_GetConcernResponse_descriptor;
      }

      @java.lang.Override
      public core.api.proto.ConcernService.GetConcernResponse getDefaultInstanceForType() {
        return core.api.proto.ConcernService.GetConcernResponse.getDefaultInstance();
      }

      @java.lang.Override
      public core.api.proto.ConcernService.GetConcernResponse build() {
        core.api.proto.ConcernService.GetConcernResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public core.api.proto.ConcernService.GetConcernResponse buildPartial() {
        core.api.proto.ConcernService.GetConcernResponse result = new core.api.proto.ConcernService.GetConcernResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(core.api.proto.ConcernService.GetConcernResponse result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.concern_ = concernBuilder_ == null
              ? concern_
              : concernBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.status_ = status_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof core.api.proto.ConcernService.GetConcernResponse) {
          return mergeFrom((core.api.proto.ConcernService.GetConcernResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(core.api.proto.ConcernService.GetConcernResponse other) {
        if (other == core.api.proto.ConcernService.GetConcernResponse.getDefaultInstance()) return this;
        if (other.hasConcern()) {
          mergeConcern(other.getConcern());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getConcernFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                int tmpRaw = input.readEnum();
                core.api.proto.ConcernService.GetConcernStatus tmpValue =
                    core.api.proto.ConcernService.GetConcernStatus.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(2, tmpRaw);
                } else {
                  status_ = tmpRaw;
                  bitField0_ |= 0x00000002;
                }
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private core.api.proto.ConcernService.RenderableConcern concern_;
      private com.google.protobuf.SingleFieldBuilderV3<
          core.api.proto.ConcernService.RenderableConcern, core.api.proto.ConcernService.RenderableConcern.Builder, core.api.proto.ConcernService.RenderableConcernOrBuilder> concernBuilder_;
      /**
       * <code>optional .core.api.proto.RenderableConcern concern = 1;</code>
       * @return Whether the concern field is set.
       */
      public boolean hasConcern() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .core.api.proto.RenderableConcern concern = 1;</code>
       * @return The concern.
       */
      public core.api.proto.ConcernService.RenderableConcern getConcern() {
        if (concernBuilder_ == null) {
          return concern_ == null ? core.api.proto.ConcernService.RenderableConcern.getDefaultInstance() : concern_;
        } else {
          return concernBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .core.api.proto.RenderableConcern concern = 1;</code>
       */
      public Builder setConcern(core.api.proto.ConcernService.RenderableConcern value) {
        if (concernBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          concern_ = value;
        } else {
          concernBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .core.api.proto.RenderableConcern concern = 1;</code>
       */
      public Builder setConcern(
          core.api.proto.ConcernService.RenderableConcern.Builder builderForValue) {
        if (concernBuilder_ == null) {
          concern_ = builderForValue.build();
        } else {
          concernBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .core.api.proto.RenderableConcern concern = 1;</code>
       */
      public Builder mergeConcern(core.api.proto.ConcernService.RenderableConcern value) {
        if (concernBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            concern_ != null &&
            concern_ != core.api.proto.ConcernService.RenderableConcern.getDefaultInstance()) {
            getConcernBuilder().mergeFrom(value);
          } else {
            concern_ = value;
          }
        } else {
          concernBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .core.api.proto.RenderableConcern concern = 1;</code>
       */
      public Builder clearConcern() {
        bitField0_ = (bitField0_ & ~0x00000001);
        concern_ = null;
        if (concernBuilder_ != null) {
          concernBuilder_.dispose();
          concernBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .core.api.proto.RenderableConcern concern = 1;</code>
       */
      public core.api.proto.ConcernService.RenderableConcern.Builder getConcernBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getConcernFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .core.api.proto.RenderableConcern concern = 1;</code>
       */
      public core.api.proto.ConcernService.RenderableConcernOrBuilder getConcernOrBuilder() {
        if (concernBuilder_ != null) {
          return concernBuilder_.getMessageOrBuilder();
        } else {
          return concern_ == null ?
              core.api.proto.ConcernService.RenderableConcern.getDefaultInstance() : concern_;
        }
      }
      /**
       * <code>optional .core.api.proto.RenderableConcern concern = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          core.api.proto.ConcernService.RenderableConcern, core.api.proto.ConcernService.RenderableConcern.Builder, core.api.proto.ConcernService.RenderableConcernOrBuilder> 
          getConcernFieldBuilder() {
        if (concernBuilder_ == null) {
          concernBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              core.api.proto.ConcernService.RenderableConcern, core.api.proto.ConcernService.RenderableConcern.Builder, core.api.proto.ConcernService.RenderableConcernOrBuilder>(
                  getConcern(),
                  getParentForChildren(),
                  isClean());
          concern_ = null;
        }
        return concernBuilder_;
      }

      private int status_ = 0;
      /**
       * <code>optional .core.api.proto.GetConcernStatus status = 2;</code>
       * @return Whether the status field is set.
       */
      @java.lang.Override public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .core.api.proto.GetConcernStatus status = 2;</code>
       * @return The status.
       */
      @java.lang.Override
      public core.api.proto.ConcernService.GetConcernStatus getStatus() {
        core.api.proto.ConcernService.GetConcernStatus result = core.api.proto.ConcernService.GetConcernStatus.forNumber(status_);
        return result == null ? core.api.proto.ConcernService.GetConcernStatus.GET_CONCERN_STATUS_UNKNOWN : result;
      }
      /**
       * <code>optional .core.api.proto.GetConcernStatus status = 2;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(core.api.proto.ConcernService.GetConcernStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .core.api.proto.GetConcernStatus status = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:core.api.proto.GetConcernResponse)
    }

    // @@protoc_insertion_point(class_scope:core.api.proto.GetConcernResponse)
    private static final core.api.proto.ConcernService.GetConcernResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new core.api.proto.ConcernService.GetConcernResponse();
    }

    public static core.api.proto.ConcernService.GetConcernResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GetConcernResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetConcernResponse>() {
      @java.lang.Override
      public GetConcernResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetConcernResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetConcernResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public core.api.proto.ConcernService.GetConcernResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_api_proto_RenderableConcern_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_api_proto_RenderableConcern_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_api_proto_GetConcernRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_api_proto_GetConcernRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_api_proto_GetConcernResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_api_proto_GetConcernResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025concern_service.proto\022\016core.api.proto\032" +
      "\rsources.proto\"\206\001\n\021RenderableConcern\022\022\n\n" +
      "concern_id\030\001 \001(\004\022\r\n\005title\030\002 \001(\t\022\017\n\007previ" +
      "ew\030\003 \001(\t\022\013\n\003url\030\004 \001(\t\0220\n\006source\030\005 \001(\0132 ." +
      "core.api.proto.RenderableSource\"\'\n\021GetCo" +
      "ncernRequest\022\022\n\nconcern_id\030\001 \001(\004\"z\n\022GetC" +
      "oncernResponse\0222\n\007concern\030\001 \001(\0132!.core.a" +
      "pi.proto.RenderableConcern\0220\n\006status\030\002 \001" +
      "(\0162 .core.api.proto.GetConcernStatus*w\n\020" +
      "GetConcernStatus\022\036\n\032GET_CONCERN_STATUS_U" +
      "NKNOWN\020\000\022\031\n\025GET_CONCERN_STATUS_OK\020\001\022(\n$G" +
      "ET_CONCERN_STATUS_CONCERN_NOT_FOUND\020\0022f\n" +
      "\016ConcernFetcher\022T\n\nGetConcern\022!.core.api" +
      ".proto.GetConcernRequest\032!.core.api.prot" +
      "o.RenderableConcern\"\000B\tH\003\242\002\004SUIP"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          core.api.proto.Sources.getDescriptor(),
        });
    internal_static_core_api_proto_RenderableConcern_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_core_api_proto_RenderableConcern_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_api_proto_RenderableConcern_descriptor,
        new java.lang.String[] { "ConcernId", "Title", "Preview", "Url", "Source", });
    internal_static_core_api_proto_GetConcernRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_core_api_proto_GetConcernRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_api_proto_GetConcernRequest_descriptor,
        new java.lang.String[] { "ConcernId", });
    internal_static_core_api_proto_GetConcernResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_core_api_proto_GetConcernResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_api_proto_GetConcernResponse_descriptor,
        new java.lang.String[] { "Concern", "Status", });
    core.api.proto.Sources.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
