// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inbox_service.proto

package core.api.proto;

public final class InboxService {
  private InboxService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InboxSegmentUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:core.api.proto.InboxSegmentUpdate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 inbox_segment_id = 1;</code>
     * @return Whether the inboxSegmentId field is set.
     */
    boolean hasInboxSegmentId();
    /**
     * <code>optional uint64 inbox_segment_id = 1;</code>
     * @return The inboxSegmentId.
     */
    long getInboxSegmentId();

    /**
     * <code>optional uint64 parent_concern_id = 2;</code>
     * @return Whether the parentConcernId field is set.
     */
    boolean hasParentConcernId();
    /**
     * <code>optional uint64 parent_concern_id = 2;</code>
     * @return The parentConcernId.
     */
    long getParentConcernId();

    /**
     * <code>optional string title = 3;</code>
     * @return Whether the title field is set.
     */
    boolean hasTitle();
    /**
     * <code>optional string title = 3;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 3;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>optional uint32 start_index = 4;</code>
     * @return Whether the startIndex field is set.
     */
    boolean hasStartIndex();
    /**
     * <code>optional uint32 start_index = 4;</code>
     * @return The startIndex.
     */
    int getStartIndex();

    /**
     * <code>optional uint32 total_available_concerns = 5;</code>
     * @return Whether the totalAvailableConcerns field is set.
     */
    boolean hasTotalAvailableConcerns();
    /**
     * <code>optional uint32 total_available_concerns = 5;</code>
     * @return The totalAvailableConcerns.
     */
    int getTotalAvailableConcerns();

    /**
     * <code>repeated uint64 concern_id_to_insert = 6;</code>
     * @return A list containing the concernIdToInsert.
     */
    java.util.List<java.lang.Long> getConcernIdToInsertList();
    /**
     * <code>repeated uint64 concern_id_to_insert = 6;</code>
     * @return The count of concernIdToInsert.
     */
    int getConcernIdToInsertCount();
    /**
     * <code>repeated uint64 concern_id_to_insert = 6;</code>
     * @param index The index of the element to return.
     * @return The concernIdToInsert at the given index.
     */
    long getConcernIdToInsert(int index);

    /**
     * <code>optional bool async_fetch_in_progress = 7;</code>
     * @return Whether the asyncFetchInProgress field is set.
     */
    boolean hasAsyncFetchInProgress();
    /**
     * <code>optional bool async_fetch_in_progress = 7;</code>
     * @return The asyncFetchInProgress.
     */
    boolean getAsyncFetchInProgress();
  }
  /**
   * Protobuf type {@code core.api.proto.InboxSegmentUpdate}
   */
  public static final class InboxSegmentUpdate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:core.api.proto.InboxSegmentUpdate)
      InboxSegmentUpdateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InboxSegmentUpdate.newBuilder() to construct.
    private InboxSegmentUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InboxSegmentUpdate() {
      title_ = "";
      concernIdToInsert_ = emptyLongList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InboxSegmentUpdate();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return core.api.proto.InboxService.internal_static_core_api_proto_InboxSegmentUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return core.api.proto.InboxService.internal_static_core_api_proto_InboxSegmentUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              core.api.proto.InboxService.InboxSegmentUpdate.class, core.api.proto.InboxService.InboxSegmentUpdate.Builder.class);
    }

    private int bitField0_;
    public static final int INBOX_SEGMENT_ID_FIELD_NUMBER = 1;
    private long inboxSegmentId_ = 0L;
    /**
     * <code>optional uint64 inbox_segment_id = 1;</code>
     * @return Whether the inboxSegmentId field is set.
     */
    @java.lang.Override
    public boolean hasInboxSegmentId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 inbox_segment_id = 1;</code>
     * @return The inboxSegmentId.
     */
    @java.lang.Override
    public long getInboxSegmentId() {
      return inboxSegmentId_;
    }

    public static final int PARENT_CONCERN_ID_FIELD_NUMBER = 2;
    private long parentConcernId_ = 0L;
    /**
     * <code>optional uint64 parent_concern_id = 2;</code>
     * @return Whether the parentConcernId field is set.
     */
    @java.lang.Override
    public boolean hasParentConcernId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint64 parent_concern_id = 2;</code>
     * @return The parentConcernId.
     */
    @java.lang.Override
    public long getParentConcernId() {
      return parentConcernId_;
    }

    public static final int TITLE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object title_ = "";
    /**
     * <code>optional string title = 3;</code>
     * @return Whether the title field is set.
     */
    @java.lang.Override
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string title = 3;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string title = 3;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_INDEX_FIELD_NUMBER = 4;
    private int startIndex_ = 0;
    /**
     * <code>optional uint32 start_index = 4;</code>
     * @return Whether the startIndex field is set.
     */
    @java.lang.Override
    public boolean hasStartIndex() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint32 start_index = 4;</code>
     * @return The startIndex.
     */
    @java.lang.Override
    public int getStartIndex() {
      return startIndex_;
    }

    public static final int TOTAL_AVAILABLE_CONCERNS_FIELD_NUMBER = 5;
    private int totalAvailableConcerns_ = 0;
    /**
     * <code>optional uint32 total_available_concerns = 5;</code>
     * @return Whether the totalAvailableConcerns field is set.
     */
    @java.lang.Override
    public boolean hasTotalAvailableConcerns() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint32 total_available_concerns = 5;</code>
     * @return The totalAvailableConcerns.
     */
    @java.lang.Override
    public int getTotalAvailableConcerns() {
      return totalAvailableConcerns_;
    }

    public static final int CONCERN_ID_TO_INSERT_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.LongList concernIdToInsert_;
    /**
     * <code>repeated uint64 concern_id_to_insert = 6;</code>
     * @return A list containing the concernIdToInsert.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getConcernIdToInsertList() {
      return concernIdToInsert_;
    }
    /**
     * <code>repeated uint64 concern_id_to_insert = 6;</code>
     * @return The count of concernIdToInsert.
     */
    public int getConcernIdToInsertCount() {
      return concernIdToInsert_.size();
    }
    /**
     * <code>repeated uint64 concern_id_to_insert = 6;</code>
     * @param index The index of the element to return.
     * @return The concernIdToInsert at the given index.
     */
    public long getConcernIdToInsert(int index) {
      return concernIdToInsert_.getLong(index);
    }

    public static final int ASYNC_FETCH_IN_PROGRESS_FIELD_NUMBER = 7;
    private boolean asyncFetchInProgress_ = false;
    /**
     * <code>optional bool async_fetch_in_progress = 7;</code>
     * @return Whether the asyncFetchInProgress field is set.
     */
    @java.lang.Override
    public boolean hasAsyncFetchInProgress() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional bool async_fetch_in_progress = 7;</code>
     * @return The asyncFetchInProgress.
     */
    @java.lang.Override
    public boolean getAsyncFetchInProgress() {
      return asyncFetchInProgress_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, inboxSegmentId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt64(2, parentConcernId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, title_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt32(4, startIndex_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeUInt32(5, totalAvailableConcerns_);
      }
      for (int i = 0; i < concernIdToInsert_.size(); i++) {
        output.writeUInt64(6, concernIdToInsert_.getLong(i));
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeBool(7, asyncFetchInProgress_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, inboxSegmentId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, parentConcernId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, title_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, startIndex_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, totalAvailableConcerns_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < concernIdToInsert_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt64SizeNoTag(concernIdToInsert_.getLong(i));
        }
        size += dataSize;
        size += 1 * getConcernIdToInsertList().size();
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, asyncFetchInProgress_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof core.api.proto.InboxService.InboxSegmentUpdate)) {
        return super.equals(obj);
      }
      core.api.proto.InboxService.InboxSegmentUpdate other = (core.api.proto.InboxService.InboxSegmentUpdate) obj;

      if (hasInboxSegmentId() != other.hasInboxSegmentId()) return false;
      if (hasInboxSegmentId()) {
        if (getInboxSegmentId()
            != other.getInboxSegmentId()) return false;
      }
      if (hasParentConcernId() != other.hasParentConcernId()) return false;
      if (hasParentConcernId()) {
        if (getParentConcernId()
            != other.getParentConcernId()) return false;
      }
      if (hasTitle() != other.hasTitle()) return false;
      if (hasTitle()) {
        if (!getTitle()
            .equals(other.getTitle())) return false;
      }
      if (hasStartIndex() != other.hasStartIndex()) return false;
      if (hasStartIndex()) {
        if (getStartIndex()
            != other.getStartIndex()) return false;
      }
      if (hasTotalAvailableConcerns() != other.hasTotalAvailableConcerns()) return false;
      if (hasTotalAvailableConcerns()) {
        if (getTotalAvailableConcerns()
            != other.getTotalAvailableConcerns()) return false;
      }
      if (!getConcernIdToInsertList()
          .equals(other.getConcernIdToInsertList())) return false;
      if (hasAsyncFetchInProgress() != other.hasAsyncFetchInProgress()) return false;
      if (hasAsyncFetchInProgress()) {
        if (getAsyncFetchInProgress()
            != other.getAsyncFetchInProgress()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasInboxSegmentId()) {
        hash = (37 * hash) + INBOX_SEGMENT_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getInboxSegmentId());
      }
      if (hasParentConcernId()) {
        hash = (37 * hash) + PARENT_CONCERN_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getParentConcernId());
      }
      if (hasTitle()) {
        hash = (37 * hash) + TITLE_FIELD_NUMBER;
        hash = (53 * hash) + getTitle().hashCode();
      }
      if (hasStartIndex()) {
        hash = (37 * hash) + START_INDEX_FIELD_NUMBER;
        hash = (53 * hash) + getStartIndex();
      }
      if (hasTotalAvailableConcerns()) {
        hash = (37 * hash) + TOTAL_AVAILABLE_CONCERNS_FIELD_NUMBER;
        hash = (53 * hash) + getTotalAvailableConcerns();
      }
      if (getConcernIdToInsertCount() > 0) {
        hash = (37 * hash) + CONCERN_ID_TO_INSERT_FIELD_NUMBER;
        hash = (53 * hash) + getConcernIdToInsertList().hashCode();
      }
      if (hasAsyncFetchInProgress()) {
        hash = (37 * hash) + ASYNC_FETCH_IN_PROGRESS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getAsyncFetchInProgress());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static core.api.proto.InboxService.InboxSegmentUpdate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.InboxService.InboxSegmentUpdate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.InboxService.InboxSegmentUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.InboxService.InboxSegmentUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.InboxService.InboxSegmentUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.InboxService.InboxSegmentUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.InboxService.InboxSegmentUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static core.api.proto.InboxService.InboxSegmentUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static core.api.proto.InboxService.InboxSegmentUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static core.api.proto.InboxService.InboxSegmentUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static core.api.proto.InboxService.InboxSegmentUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static core.api.proto.InboxService.InboxSegmentUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(core.api.proto.InboxService.InboxSegmentUpdate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code core.api.proto.InboxSegmentUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:core.api.proto.InboxSegmentUpdate)
        core.api.proto.InboxService.InboxSegmentUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return core.api.proto.InboxService.internal_static_core_api_proto_InboxSegmentUpdate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return core.api.proto.InboxService.internal_static_core_api_proto_InboxSegmentUpdate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                core.api.proto.InboxService.InboxSegmentUpdate.class, core.api.proto.InboxService.InboxSegmentUpdate.Builder.class);
      }

      // Construct using core.api.proto.InboxService.InboxSegmentUpdate.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        inboxSegmentId_ = 0L;
        parentConcernId_ = 0L;
        title_ = "";
        startIndex_ = 0;
        totalAvailableConcerns_ = 0;
        concernIdToInsert_ = emptyLongList();
        asyncFetchInProgress_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return core.api.proto.InboxService.internal_static_core_api_proto_InboxSegmentUpdate_descriptor;
      }

      @java.lang.Override
      public core.api.proto.InboxService.InboxSegmentUpdate getDefaultInstanceForType() {
        return core.api.proto.InboxService.InboxSegmentUpdate.getDefaultInstance();
      }

      @java.lang.Override
      public core.api.proto.InboxService.InboxSegmentUpdate build() {
        core.api.proto.InboxService.InboxSegmentUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public core.api.proto.InboxService.InboxSegmentUpdate buildPartial() {
        core.api.proto.InboxService.InboxSegmentUpdate result = new core.api.proto.InboxService.InboxSegmentUpdate(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(core.api.proto.InboxService.InboxSegmentUpdate result) {
        if (((bitField0_ & 0x00000020) != 0)) {
          concernIdToInsert_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.concernIdToInsert_ = concernIdToInsert_;
      }

      private void buildPartial0(core.api.proto.InboxService.InboxSegmentUpdate result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.inboxSegmentId_ = inboxSegmentId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.parentConcernId_ = parentConcernId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.title_ = title_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.startIndex_ = startIndex_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.totalAvailableConcerns_ = totalAvailableConcerns_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.asyncFetchInProgress_ = asyncFetchInProgress_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof core.api.proto.InboxService.InboxSegmentUpdate) {
          return mergeFrom((core.api.proto.InboxService.InboxSegmentUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(core.api.proto.InboxService.InboxSegmentUpdate other) {
        if (other == core.api.proto.InboxService.InboxSegmentUpdate.getDefaultInstance()) return this;
        if (other.hasInboxSegmentId()) {
          setInboxSegmentId(other.getInboxSegmentId());
        }
        if (other.hasParentConcernId()) {
          setParentConcernId(other.getParentConcernId());
        }
        if (other.hasTitle()) {
          title_ = other.title_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasStartIndex()) {
          setStartIndex(other.getStartIndex());
        }
        if (other.hasTotalAvailableConcerns()) {
          setTotalAvailableConcerns(other.getTotalAvailableConcerns());
        }
        if (!other.concernIdToInsert_.isEmpty()) {
          if (concernIdToInsert_.isEmpty()) {
            concernIdToInsert_ = other.concernIdToInsert_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureConcernIdToInsertIsMutable();
            concernIdToInsert_.addAll(other.concernIdToInsert_);
          }
          onChanged();
        }
        if (other.hasAsyncFetchInProgress()) {
          setAsyncFetchInProgress(other.getAsyncFetchInProgress());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                inboxSegmentId_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                parentConcernId_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                title_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                startIndex_ = input.readUInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                totalAvailableConcerns_ = input.readUInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                long v = input.readUInt64();
                ensureConcernIdToInsertIsMutable();
                concernIdToInsert_.addLong(v);
                break;
              } // case 48
              case 50: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureConcernIdToInsertIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  concernIdToInsert_.addLong(input.readUInt64());
                }
                input.popLimit(limit);
                break;
              } // case 50
              case 56: {
                asyncFetchInProgress_ = input.readBool();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long inboxSegmentId_ ;
      /**
       * <code>optional uint64 inbox_segment_id = 1;</code>
       * @return Whether the inboxSegmentId field is set.
       */
      @java.lang.Override
      public boolean hasInboxSegmentId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint64 inbox_segment_id = 1;</code>
       * @return The inboxSegmentId.
       */
      @java.lang.Override
      public long getInboxSegmentId() {
        return inboxSegmentId_;
      }
      /**
       * <code>optional uint64 inbox_segment_id = 1;</code>
       * @param value The inboxSegmentId to set.
       * @return This builder for chaining.
       */
      public Builder setInboxSegmentId(long value) {

        inboxSegmentId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 inbox_segment_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInboxSegmentId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        inboxSegmentId_ = 0L;
        onChanged();
        return this;
      }

      private long parentConcernId_ ;
      /**
       * <code>optional uint64 parent_concern_id = 2;</code>
       * @return Whether the parentConcernId field is set.
       */
      @java.lang.Override
      public boolean hasParentConcernId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional uint64 parent_concern_id = 2;</code>
       * @return The parentConcernId.
       */
      @java.lang.Override
      public long getParentConcernId() {
        return parentConcernId_;
      }
      /**
       * <code>optional uint64 parent_concern_id = 2;</code>
       * @param value The parentConcernId to set.
       * @return This builder for chaining.
       */
      public Builder setParentConcernId(long value) {

        parentConcernId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 parent_concern_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearParentConcernId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        parentConcernId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>optional string title = 3;</code>
       * @return Whether the title field is set.
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string title = 3;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string title = 3;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string title = 3;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        title_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        title_ = getDefaultInstance().getTitle();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 3;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        title_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int startIndex_ ;
      /**
       * <code>optional uint32 start_index = 4;</code>
       * @return Whether the startIndex field is set.
       */
      @java.lang.Override
      public boolean hasStartIndex() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional uint32 start_index = 4;</code>
       * @return The startIndex.
       */
      @java.lang.Override
      public int getStartIndex() {
        return startIndex_;
      }
      /**
       * <code>optional uint32 start_index = 4;</code>
       * @param value The startIndex to set.
       * @return This builder for chaining.
       */
      public Builder setStartIndex(int value) {

        startIndex_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 start_index = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartIndex() {
        bitField0_ = (bitField0_ & ~0x00000008);
        startIndex_ = 0;
        onChanged();
        return this;
      }

      private int totalAvailableConcerns_ ;
      /**
       * <code>optional uint32 total_available_concerns = 5;</code>
       * @return Whether the totalAvailableConcerns field is set.
       */
      @java.lang.Override
      public boolean hasTotalAvailableConcerns() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional uint32 total_available_concerns = 5;</code>
       * @return The totalAvailableConcerns.
       */
      @java.lang.Override
      public int getTotalAvailableConcerns() {
        return totalAvailableConcerns_;
      }
      /**
       * <code>optional uint32 total_available_concerns = 5;</code>
       * @param value The totalAvailableConcerns to set.
       * @return This builder for chaining.
       */
      public Builder setTotalAvailableConcerns(int value) {

        totalAvailableConcerns_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 total_available_concerns = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalAvailableConcerns() {
        bitField0_ = (bitField0_ & ~0x00000010);
        totalAvailableConcerns_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.LongList concernIdToInsert_ = emptyLongList();
      private void ensureConcernIdToInsertIsMutable() {
        if (!((bitField0_ & 0x00000020) != 0)) {
          concernIdToInsert_ = mutableCopy(concernIdToInsert_);
          bitField0_ |= 0x00000020;
        }
      }
      /**
       * <code>repeated uint64 concern_id_to_insert = 6;</code>
       * @return A list containing the concernIdToInsert.
       */
      public java.util.List<java.lang.Long>
          getConcernIdToInsertList() {
        return ((bitField0_ & 0x00000020) != 0) ?
                 java.util.Collections.unmodifiableList(concernIdToInsert_) : concernIdToInsert_;
      }
      /**
       * <code>repeated uint64 concern_id_to_insert = 6;</code>
       * @return The count of concernIdToInsert.
       */
      public int getConcernIdToInsertCount() {
        return concernIdToInsert_.size();
      }
      /**
       * <code>repeated uint64 concern_id_to_insert = 6;</code>
       * @param index The index of the element to return.
       * @return The concernIdToInsert at the given index.
       */
      public long getConcernIdToInsert(int index) {
        return concernIdToInsert_.getLong(index);
      }
      /**
       * <code>repeated uint64 concern_id_to_insert = 6;</code>
       * @param index The index to set the value at.
       * @param value The concernIdToInsert to set.
       * @return This builder for chaining.
       */
      public Builder setConcernIdToInsert(
          int index, long value) {

        ensureConcernIdToInsertIsMutable();
        concernIdToInsert_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 concern_id_to_insert = 6;</code>
       * @param value The concernIdToInsert to add.
       * @return This builder for chaining.
       */
      public Builder addConcernIdToInsert(long value) {

        ensureConcernIdToInsertIsMutable();
        concernIdToInsert_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 concern_id_to_insert = 6;</code>
       * @param values The concernIdToInsert to add.
       * @return This builder for chaining.
       */
      public Builder addAllConcernIdToInsert(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureConcernIdToInsertIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, concernIdToInsert_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 concern_id_to_insert = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearConcernIdToInsert() {
        concernIdToInsert_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }

      private boolean asyncFetchInProgress_ ;
      /**
       * <code>optional bool async_fetch_in_progress = 7;</code>
       * @return Whether the asyncFetchInProgress field is set.
       */
      @java.lang.Override
      public boolean hasAsyncFetchInProgress() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional bool async_fetch_in_progress = 7;</code>
       * @return The asyncFetchInProgress.
       */
      @java.lang.Override
      public boolean getAsyncFetchInProgress() {
        return asyncFetchInProgress_;
      }
      /**
       * <code>optional bool async_fetch_in_progress = 7;</code>
       * @param value The asyncFetchInProgress to set.
       * @return This builder for chaining.
       */
      public Builder setAsyncFetchInProgress(boolean value) {

        asyncFetchInProgress_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool async_fetch_in_progress = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAsyncFetchInProgress() {
        bitField0_ = (bitField0_ & ~0x00000040);
        asyncFetchInProgress_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:core.api.proto.InboxSegmentUpdate)
    }

    // @@protoc_insertion_point(class_scope:core.api.proto.InboxSegmentUpdate)
    private static final core.api.proto.InboxService.InboxSegmentUpdate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new core.api.proto.InboxService.InboxSegmentUpdate();
    }

    public static core.api.proto.InboxService.InboxSegmentUpdate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<InboxSegmentUpdate>
        PARSER = new com.google.protobuf.AbstractParser<InboxSegmentUpdate>() {
      @java.lang.Override
      public InboxSegmentUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<InboxSegmentUpdate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InboxSegmentUpdate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public core.api.proto.InboxService.InboxSegmentUpdate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetInboxSegmentRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:core.api.proto.GetInboxSegmentRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 parent_concern_id = 1;</code>
     * @return Whether the parentConcernId field is set.
     */
    boolean hasParentConcernId();
    /**
     * <code>optional uint64 parent_concern_id = 1;</code>
     * @return The parentConcernId.
     */
    long getParentConcernId();

    /**
     * <code>optional uint64 previous_inbox_segment_id = 2;</code>
     * @return Whether the previousInboxSegmentId field is set.
     */
    boolean hasPreviousInboxSegmentId();
    /**
     * <code>optional uint64 previous_inbox_segment_id = 2;</code>
     * @return The previousInboxSegmentId.
     */
    long getPreviousInboxSegmentId();

    /**
     * <code>repeated uint64 current_segment_inserted_concern_ids = 3;</code>
     * @return A list containing the currentSegmentInsertedConcernIds.
     */
    java.util.List<java.lang.Long> getCurrentSegmentInsertedConcernIdsList();
    /**
     * <code>repeated uint64 current_segment_inserted_concern_ids = 3;</code>
     * @return The count of currentSegmentInsertedConcernIds.
     */
    int getCurrentSegmentInsertedConcernIdsCount();
    /**
     * <code>repeated uint64 current_segment_inserted_concern_ids = 3;</code>
     * @param index The index of the element to return.
     * @return The currentSegmentInsertedConcernIds at the given index.
     */
    long getCurrentSegmentInsertedConcernIds(int index);
  }
  /**
   * Protobuf type {@code core.api.proto.GetInboxSegmentRequest}
   */
  public static final class GetInboxSegmentRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:core.api.proto.GetInboxSegmentRequest)
      GetInboxSegmentRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetInboxSegmentRequest.newBuilder() to construct.
    private GetInboxSegmentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetInboxSegmentRequest() {
      currentSegmentInsertedConcernIds_ = emptyLongList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetInboxSegmentRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return core.api.proto.InboxService.internal_static_core_api_proto_GetInboxSegmentRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return core.api.proto.InboxService.internal_static_core_api_proto_GetInboxSegmentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              core.api.proto.InboxService.GetInboxSegmentRequest.class, core.api.proto.InboxService.GetInboxSegmentRequest.Builder.class);
    }

    private int bitField0_;
    public static final int PARENT_CONCERN_ID_FIELD_NUMBER = 1;
    private long parentConcernId_ = 0L;
    /**
     * <code>optional uint64 parent_concern_id = 1;</code>
     * @return Whether the parentConcernId field is set.
     */
    @java.lang.Override
    public boolean hasParentConcernId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 parent_concern_id = 1;</code>
     * @return The parentConcernId.
     */
    @java.lang.Override
    public long getParentConcernId() {
      return parentConcernId_;
    }

    public static final int PREVIOUS_INBOX_SEGMENT_ID_FIELD_NUMBER = 2;
    private long previousInboxSegmentId_ = 0L;
    /**
     * <code>optional uint64 previous_inbox_segment_id = 2;</code>
     * @return Whether the previousInboxSegmentId field is set.
     */
    @java.lang.Override
    public boolean hasPreviousInboxSegmentId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint64 previous_inbox_segment_id = 2;</code>
     * @return The previousInboxSegmentId.
     */
    @java.lang.Override
    public long getPreviousInboxSegmentId() {
      return previousInboxSegmentId_;
    }

    public static final int CURRENT_SEGMENT_INSERTED_CONCERN_IDS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.LongList currentSegmentInsertedConcernIds_;
    /**
     * <code>repeated uint64 current_segment_inserted_concern_ids = 3;</code>
     * @return A list containing the currentSegmentInsertedConcernIds.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getCurrentSegmentInsertedConcernIdsList() {
      return currentSegmentInsertedConcernIds_;
    }
    /**
     * <code>repeated uint64 current_segment_inserted_concern_ids = 3;</code>
     * @return The count of currentSegmentInsertedConcernIds.
     */
    public int getCurrentSegmentInsertedConcernIdsCount() {
      return currentSegmentInsertedConcernIds_.size();
    }
    /**
     * <code>repeated uint64 current_segment_inserted_concern_ids = 3;</code>
     * @param index The index of the element to return.
     * @return The currentSegmentInsertedConcernIds at the given index.
     */
    public long getCurrentSegmentInsertedConcernIds(int index) {
      return currentSegmentInsertedConcernIds_.getLong(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, parentConcernId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt64(2, previousInboxSegmentId_);
      }
      for (int i = 0; i < currentSegmentInsertedConcernIds_.size(); i++) {
        output.writeUInt64(3, currentSegmentInsertedConcernIds_.getLong(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, parentConcernId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, previousInboxSegmentId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < currentSegmentInsertedConcernIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt64SizeNoTag(currentSegmentInsertedConcernIds_.getLong(i));
        }
        size += dataSize;
        size += 1 * getCurrentSegmentInsertedConcernIdsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof core.api.proto.InboxService.GetInboxSegmentRequest)) {
        return super.equals(obj);
      }
      core.api.proto.InboxService.GetInboxSegmentRequest other = (core.api.proto.InboxService.GetInboxSegmentRequest) obj;

      if (hasParentConcernId() != other.hasParentConcernId()) return false;
      if (hasParentConcernId()) {
        if (getParentConcernId()
            != other.getParentConcernId()) return false;
      }
      if (hasPreviousInboxSegmentId() != other.hasPreviousInboxSegmentId()) return false;
      if (hasPreviousInboxSegmentId()) {
        if (getPreviousInboxSegmentId()
            != other.getPreviousInboxSegmentId()) return false;
      }
      if (!getCurrentSegmentInsertedConcernIdsList()
          .equals(other.getCurrentSegmentInsertedConcernIdsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasParentConcernId()) {
        hash = (37 * hash) + PARENT_CONCERN_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getParentConcernId());
      }
      if (hasPreviousInboxSegmentId()) {
        hash = (37 * hash) + PREVIOUS_INBOX_SEGMENT_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPreviousInboxSegmentId());
      }
      if (getCurrentSegmentInsertedConcernIdsCount() > 0) {
        hash = (37 * hash) + CURRENT_SEGMENT_INSERTED_CONCERN_IDS_FIELD_NUMBER;
        hash = (53 * hash) + getCurrentSegmentInsertedConcernIdsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static core.api.proto.InboxService.GetInboxSegmentRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.InboxService.GetInboxSegmentRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.InboxService.GetInboxSegmentRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.InboxService.GetInboxSegmentRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.InboxService.GetInboxSegmentRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.InboxService.GetInboxSegmentRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.InboxService.GetInboxSegmentRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static core.api.proto.InboxService.GetInboxSegmentRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static core.api.proto.InboxService.GetInboxSegmentRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static core.api.proto.InboxService.GetInboxSegmentRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static core.api.proto.InboxService.GetInboxSegmentRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static core.api.proto.InboxService.GetInboxSegmentRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(core.api.proto.InboxService.GetInboxSegmentRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code core.api.proto.GetInboxSegmentRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:core.api.proto.GetInboxSegmentRequest)
        core.api.proto.InboxService.GetInboxSegmentRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return core.api.proto.InboxService.internal_static_core_api_proto_GetInboxSegmentRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return core.api.proto.InboxService.internal_static_core_api_proto_GetInboxSegmentRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                core.api.proto.InboxService.GetInboxSegmentRequest.class, core.api.proto.InboxService.GetInboxSegmentRequest.Builder.class);
      }

      // Construct using core.api.proto.InboxService.GetInboxSegmentRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        parentConcernId_ = 0L;
        previousInboxSegmentId_ = 0L;
        currentSegmentInsertedConcernIds_ = emptyLongList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return core.api.proto.InboxService.internal_static_core_api_proto_GetInboxSegmentRequest_descriptor;
      }

      @java.lang.Override
      public core.api.proto.InboxService.GetInboxSegmentRequest getDefaultInstanceForType() {
        return core.api.proto.InboxService.GetInboxSegmentRequest.getDefaultInstance();
      }

      @java.lang.Override
      public core.api.proto.InboxService.GetInboxSegmentRequest build() {
        core.api.proto.InboxService.GetInboxSegmentRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public core.api.proto.InboxService.GetInboxSegmentRequest buildPartial() {
        core.api.proto.InboxService.GetInboxSegmentRequest result = new core.api.proto.InboxService.GetInboxSegmentRequest(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(core.api.proto.InboxService.GetInboxSegmentRequest result) {
        if (((bitField0_ & 0x00000004) != 0)) {
          currentSegmentInsertedConcernIds_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.currentSegmentInsertedConcernIds_ = currentSegmentInsertedConcernIds_;
      }

      private void buildPartial0(core.api.proto.InboxService.GetInboxSegmentRequest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.parentConcernId_ = parentConcernId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.previousInboxSegmentId_ = previousInboxSegmentId_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof core.api.proto.InboxService.GetInboxSegmentRequest) {
          return mergeFrom((core.api.proto.InboxService.GetInboxSegmentRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(core.api.proto.InboxService.GetInboxSegmentRequest other) {
        if (other == core.api.proto.InboxService.GetInboxSegmentRequest.getDefaultInstance()) return this;
        if (other.hasParentConcernId()) {
          setParentConcernId(other.getParentConcernId());
        }
        if (other.hasPreviousInboxSegmentId()) {
          setPreviousInboxSegmentId(other.getPreviousInboxSegmentId());
        }
        if (!other.currentSegmentInsertedConcernIds_.isEmpty()) {
          if (currentSegmentInsertedConcernIds_.isEmpty()) {
            currentSegmentInsertedConcernIds_ = other.currentSegmentInsertedConcernIds_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureCurrentSegmentInsertedConcernIdsIsMutable();
            currentSegmentInsertedConcernIds_.addAll(other.currentSegmentInsertedConcernIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                parentConcernId_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                previousInboxSegmentId_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                long v = input.readUInt64();
                ensureCurrentSegmentInsertedConcernIdsIsMutable();
                currentSegmentInsertedConcernIds_.addLong(v);
                break;
              } // case 24
              case 26: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureCurrentSegmentInsertedConcernIdsIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  currentSegmentInsertedConcernIds_.addLong(input.readUInt64());
                }
                input.popLimit(limit);
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long parentConcernId_ ;
      /**
       * <code>optional uint64 parent_concern_id = 1;</code>
       * @return Whether the parentConcernId field is set.
       */
      @java.lang.Override
      public boolean hasParentConcernId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint64 parent_concern_id = 1;</code>
       * @return The parentConcernId.
       */
      @java.lang.Override
      public long getParentConcernId() {
        return parentConcernId_;
      }
      /**
       * <code>optional uint64 parent_concern_id = 1;</code>
       * @param value The parentConcernId to set.
       * @return This builder for chaining.
       */
      public Builder setParentConcernId(long value) {

        parentConcernId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 parent_concern_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearParentConcernId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        parentConcernId_ = 0L;
        onChanged();
        return this;
      }

      private long previousInboxSegmentId_ ;
      /**
       * <code>optional uint64 previous_inbox_segment_id = 2;</code>
       * @return Whether the previousInboxSegmentId field is set.
       */
      @java.lang.Override
      public boolean hasPreviousInboxSegmentId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional uint64 previous_inbox_segment_id = 2;</code>
       * @return The previousInboxSegmentId.
       */
      @java.lang.Override
      public long getPreviousInboxSegmentId() {
        return previousInboxSegmentId_;
      }
      /**
       * <code>optional uint64 previous_inbox_segment_id = 2;</code>
       * @param value The previousInboxSegmentId to set.
       * @return This builder for chaining.
       */
      public Builder setPreviousInboxSegmentId(long value) {

        previousInboxSegmentId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 previous_inbox_segment_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPreviousInboxSegmentId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        previousInboxSegmentId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.LongList currentSegmentInsertedConcernIds_ = emptyLongList();
      private void ensureCurrentSegmentInsertedConcernIdsIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          currentSegmentInsertedConcernIds_ = mutableCopy(currentSegmentInsertedConcernIds_);
          bitField0_ |= 0x00000004;
        }
      }
      /**
       * <code>repeated uint64 current_segment_inserted_concern_ids = 3;</code>
       * @return A list containing the currentSegmentInsertedConcernIds.
       */
      public java.util.List<java.lang.Long>
          getCurrentSegmentInsertedConcernIdsList() {
        return ((bitField0_ & 0x00000004) != 0) ?
                 java.util.Collections.unmodifiableList(currentSegmentInsertedConcernIds_) : currentSegmentInsertedConcernIds_;
      }
      /**
       * <code>repeated uint64 current_segment_inserted_concern_ids = 3;</code>
       * @return The count of currentSegmentInsertedConcernIds.
       */
      public int getCurrentSegmentInsertedConcernIdsCount() {
        return currentSegmentInsertedConcernIds_.size();
      }
      /**
       * <code>repeated uint64 current_segment_inserted_concern_ids = 3;</code>
       * @param index The index of the element to return.
       * @return The currentSegmentInsertedConcernIds at the given index.
       */
      public long getCurrentSegmentInsertedConcernIds(int index) {
        return currentSegmentInsertedConcernIds_.getLong(index);
      }
      /**
       * <code>repeated uint64 current_segment_inserted_concern_ids = 3;</code>
       * @param index The index to set the value at.
       * @param value The currentSegmentInsertedConcernIds to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentSegmentInsertedConcernIds(
          int index, long value) {

        ensureCurrentSegmentInsertedConcernIdsIsMutable();
        currentSegmentInsertedConcernIds_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 current_segment_inserted_concern_ids = 3;</code>
       * @param value The currentSegmentInsertedConcernIds to add.
       * @return This builder for chaining.
       */
      public Builder addCurrentSegmentInsertedConcernIds(long value) {

        ensureCurrentSegmentInsertedConcernIdsIsMutable();
        currentSegmentInsertedConcernIds_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 current_segment_inserted_concern_ids = 3;</code>
       * @param values The currentSegmentInsertedConcernIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllCurrentSegmentInsertedConcernIds(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureCurrentSegmentInsertedConcernIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, currentSegmentInsertedConcernIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 current_segment_inserted_concern_ids = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentSegmentInsertedConcernIds() {
        currentSegmentInsertedConcernIds_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:core.api.proto.GetInboxSegmentRequest)
    }

    // @@protoc_insertion_point(class_scope:core.api.proto.GetInboxSegmentRequest)
    private static final core.api.proto.InboxService.GetInboxSegmentRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new core.api.proto.InboxService.GetInboxSegmentRequest();
    }

    public static core.api.proto.InboxService.GetInboxSegmentRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GetInboxSegmentRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetInboxSegmentRequest>() {
      @java.lang.Override
      public GetInboxSegmentRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetInboxSegmentRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetInboxSegmentRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public core.api.proto.InboxService.GetInboxSegmentRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_api_proto_InboxSegmentUpdate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_api_proto_InboxSegmentUpdate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_api_proto_GetInboxSegmentRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_api_proto_GetInboxSegmentRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023inbox_service.proto\022\016core.api.proto\"\316\001" +
      "\n\022InboxSegmentUpdate\022\030\n\020inbox_segment_id" +
      "\030\001 \001(\004\022\031\n\021parent_concern_id\030\002 \001(\004\022\r\n\005tit" +
      "le\030\003 \001(\t\022\023\n\013start_index\030\004 \001(\r\022 \n\030total_a" +
      "vailable_concerns\030\005 \001(\r\022\034\n\024concern_id_to" +
      "_insert\030\006 \003(\004\022\037\n\027async_fetch_in_progress" +
      "\030\007 \001(\010\"\204\001\n\026GetInboxSegmentRequest\022\031\n\021par" +
      "ent_concern_id\030\001 \001(\004\022!\n\031previous_inbox_s" +
      "egment_id\030\002 \001(\004\022,\n$current_segment_inser" +
      "ted_concern_ids\030\003 \003(\0042j\n\005Inbox\022a\n\017GetInb" +
      "oxSegment\022&.core.api.proto.GetInboxSegme" +
      "ntRequest\032\".core.api.proto.InboxSegmentU" +
      "pdate\"\0000\001B\tH\003\242\002\004SUIP"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_core_api_proto_InboxSegmentUpdate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_core_api_proto_InboxSegmentUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_api_proto_InboxSegmentUpdate_descriptor,
        new java.lang.String[] { "InboxSegmentId", "ParentConcernId", "Title", "StartIndex", "TotalAvailableConcerns", "ConcernIdToInsert", "AsyncFetchInProgress", });
    internal_static_core_api_proto_GetInboxSegmentRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_core_api_proto_GetInboxSegmentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_api_proto_GetInboxSegmentRequest_descriptor,
        new java.lang.String[] { "ParentConcernId", "PreviousInboxSegmentId", "CurrentSegmentInsertedConcernIds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
