// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sources.proto

package core.api.proto;

public final class Sources {
  private Sources() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ListSourceRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:core.api.proto.ListSourceRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code core.api.proto.ListSourceRequest}
   */
  public static final class ListSourceRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:core.api.proto.ListSourceRequest)
      ListSourceRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ListSourceRequest.newBuilder() to construct.
    private ListSourceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ListSourceRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ListSourceRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return core.api.proto.Sources.internal_static_core_api_proto_ListSourceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return core.api.proto.Sources.internal_static_core_api_proto_ListSourceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              core.api.proto.Sources.ListSourceRequest.class, core.api.proto.Sources.ListSourceRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof core.api.proto.Sources.ListSourceRequest)) {
        return super.equals(obj);
      }
      core.api.proto.Sources.ListSourceRequest other = (core.api.proto.Sources.ListSourceRequest) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static core.api.proto.Sources.ListSourceRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.Sources.ListSourceRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.Sources.ListSourceRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.Sources.ListSourceRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.Sources.ListSourceRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.Sources.ListSourceRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.Sources.ListSourceRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static core.api.proto.Sources.ListSourceRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static core.api.proto.Sources.ListSourceRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static core.api.proto.Sources.ListSourceRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static core.api.proto.Sources.ListSourceRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static core.api.proto.Sources.ListSourceRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(core.api.proto.Sources.ListSourceRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code core.api.proto.ListSourceRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:core.api.proto.ListSourceRequest)
        core.api.proto.Sources.ListSourceRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return core.api.proto.Sources.internal_static_core_api_proto_ListSourceRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return core.api.proto.Sources.internal_static_core_api_proto_ListSourceRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                core.api.proto.Sources.ListSourceRequest.class, core.api.proto.Sources.ListSourceRequest.Builder.class);
      }

      // Construct using core.api.proto.Sources.ListSourceRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return core.api.proto.Sources.internal_static_core_api_proto_ListSourceRequest_descriptor;
      }

      @java.lang.Override
      public core.api.proto.Sources.ListSourceRequest getDefaultInstanceForType() {
        return core.api.proto.Sources.ListSourceRequest.getDefaultInstance();
      }

      @java.lang.Override
      public core.api.proto.Sources.ListSourceRequest build() {
        core.api.proto.Sources.ListSourceRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public core.api.proto.Sources.ListSourceRequest buildPartial() {
        core.api.proto.Sources.ListSourceRequest result = new core.api.proto.Sources.ListSourceRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof core.api.proto.Sources.ListSourceRequest) {
          return mergeFrom((core.api.proto.Sources.ListSourceRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(core.api.proto.Sources.ListSourceRequest other) {
        if (other == core.api.proto.Sources.ListSourceRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:core.api.proto.ListSourceRequest)
    }

    // @@protoc_insertion_point(class_scope:core.api.proto.ListSourceRequest)
    private static final core.api.proto.Sources.ListSourceRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new core.api.proto.Sources.ListSourceRequest();
    }

    public static core.api.proto.Sources.ListSourceRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ListSourceRequest>
        PARSER = new com.google.protobuf.AbstractParser<ListSourceRequest>() {
      @java.lang.Override
      public ListSourceRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ListSourceRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListSourceRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public core.api.proto.Sources.ListSourceRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ListSourceResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:core.api.proto.ListSourceResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
     */
    java.util.List<core.api.proto.Sources.RenderableSource> 
        getSourceList();
    /**
     * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
     */
    core.api.proto.Sources.RenderableSource getSource(int index);
    /**
     * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
     */
    int getSourceCount();
    /**
     * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
     */
    java.util.List<? extends core.api.proto.Sources.RenderableSourceOrBuilder> 
        getSourceOrBuilderList();
    /**
     * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
     */
    core.api.proto.Sources.RenderableSourceOrBuilder getSourceOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code core.api.proto.ListSourceResponse}
   */
  public static final class ListSourceResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:core.api.proto.ListSourceResponse)
      ListSourceResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ListSourceResponse.newBuilder() to construct.
    private ListSourceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ListSourceResponse() {
      source_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ListSourceResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return core.api.proto.Sources.internal_static_core_api_proto_ListSourceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return core.api.proto.Sources.internal_static_core_api_proto_ListSourceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              core.api.proto.Sources.ListSourceResponse.class, core.api.proto.Sources.ListSourceResponse.Builder.class);
    }

    public static final int SOURCE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<core.api.proto.Sources.RenderableSource> source_;
    /**
     * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
     */
    @java.lang.Override
    public java.util.List<core.api.proto.Sources.RenderableSource> getSourceList() {
      return source_;
    }
    /**
     * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends core.api.proto.Sources.RenderableSourceOrBuilder> 
        getSourceOrBuilderList() {
      return source_;
    }
    /**
     * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
     */
    @java.lang.Override
    public int getSourceCount() {
      return source_.size();
    }
    /**
     * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
     */
    @java.lang.Override
    public core.api.proto.Sources.RenderableSource getSource(int index) {
      return source_.get(index);
    }
    /**
     * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
     */
    @java.lang.Override
    public core.api.proto.Sources.RenderableSourceOrBuilder getSourceOrBuilder(
        int index) {
      return source_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < source_.size(); i++) {
        output.writeMessage(1, source_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < source_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, source_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof core.api.proto.Sources.ListSourceResponse)) {
        return super.equals(obj);
      }
      core.api.proto.Sources.ListSourceResponse other = (core.api.proto.Sources.ListSourceResponse) obj;

      if (!getSourceList()
          .equals(other.getSourceList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSourceCount() > 0) {
        hash = (37 * hash) + SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getSourceList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static core.api.proto.Sources.ListSourceResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.Sources.ListSourceResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.Sources.ListSourceResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.Sources.ListSourceResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.Sources.ListSourceResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.Sources.ListSourceResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.Sources.ListSourceResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static core.api.proto.Sources.ListSourceResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static core.api.proto.Sources.ListSourceResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static core.api.proto.Sources.ListSourceResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static core.api.proto.Sources.ListSourceResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static core.api.proto.Sources.ListSourceResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(core.api.proto.Sources.ListSourceResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code core.api.proto.ListSourceResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:core.api.proto.ListSourceResponse)
        core.api.proto.Sources.ListSourceResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return core.api.proto.Sources.internal_static_core_api_proto_ListSourceResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return core.api.proto.Sources.internal_static_core_api_proto_ListSourceResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                core.api.proto.Sources.ListSourceResponse.class, core.api.proto.Sources.ListSourceResponse.Builder.class);
      }

      // Construct using core.api.proto.Sources.ListSourceResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (sourceBuilder_ == null) {
          source_ = java.util.Collections.emptyList();
        } else {
          source_ = null;
          sourceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return core.api.proto.Sources.internal_static_core_api_proto_ListSourceResponse_descriptor;
      }

      @java.lang.Override
      public core.api.proto.Sources.ListSourceResponse getDefaultInstanceForType() {
        return core.api.proto.Sources.ListSourceResponse.getDefaultInstance();
      }

      @java.lang.Override
      public core.api.proto.Sources.ListSourceResponse build() {
        core.api.proto.Sources.ListSourceResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public core.api.proto.Sources.ListSourceResponse buildPartial() {
        core.api.proto.Sources.ListSourceResponse result = new core.api.proto.Sources.ListSourceResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(core.api.proto.Sources.ListSourceResponse result) {
        if (sourceBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            source_ = java.util.Collections.unmodifiableList(source_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.source_ = source_;
        } else {
          result.source_ = sourceBuilder_.build();
        }
      }

      private void buildPartial0(core.api.proto.Sources.ListSourceResponse result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof core.api.proto.Sources.ListSourceResponse) {
          return mergeFrom((core.api.proto.Sources.ListSourceResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(core.api.proto.Sources.ListSourceResponse other) {
        if (other == core.api.proto.Sources.ListSourceResponse.getDefaultInstance()) return this;
        if (sourceBuilder_ == null) {
          if (!other.source_.isEmpty()) {
            if (source_.isEmpty()) {
              source_ = other.source_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSourceIsMutable();
              source_.addAll(other.source_);
            }
            onChanged();
          }
        } else {
          if (!other.source_.isEmpty()) {
            if (sourceBuilder_.isEmpty()) {
              sourceBuilder_.dispose();
              sourceBuilder_ = null;
              source_ = other.source_;
              bitField0_ = (bitField0_ & ~0x00000001);
              sourceBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSourceFieldBuilder() : null;
            } else {
              sourceBuilder_.addAllMessages(other.source_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                core.api.proto.Sources.RenderableSource m =
                    input.readMessage(
                        core.api.proto.Sources.RenderableSource.PARSER,
                        extensionRegistry);
                if (sourceBuilder_ == null) {
                  ensureSourceIsMutable();
                  source_.add(m);
                } else {
                  sourceBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<core.api.proto.Sources.RenderableSource> source_ =
        java.util.Collections.emptyList();
      private void ensureSourceIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          source_ = new java.util.ArrayList<core.api.proto.Sources.RenderableSource>(source_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          core.api.proto.Sources.RenderableSource, core.api.proto.Sources.RenderableSource.Builder, core.api.proto.Sources.RenderableSourceOrBuilder> sourceBuilder_;

      /**
       * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
       */
      public java.util.List<core.api.proto.Sources.RenderableSource> getSourceList() {
        if (sourceBuilder_ == null) {
          return java.util.Collections.unmodifiableList(source_);
        } else {
          return sourceBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
       */
      public int getSourceCount() {
        if (sourceBuilder_ == null) {
          return source_.size();
        } else {
          return sourceBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
       */
      public core.api.proto.Sources.RenderableSource getSource(int index) {
        if (sourceBuilder_ == null) {
          return source_.get(index);
        } else {
          return sourceBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
       */
      public Builder setSource(
          int index, core.api.proto.Sources.RenderableSource value) {
        if (sourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSourceIsMutable();
          source_.set(index, value);
          onChanged();
        } else {
          sourceBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
       */
      public Builder setSource(
          int index, core.api.proto.Sources.RenderableSource.Builder builderForValue) {
        if (sourceBuilder_ == null) {
          ensureSourceIsMutable();
          source_.set(index, builderForValue.build());
          onChanged();
        } else {
          sourceBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
       */
      public Builder addSource(core.api.proto.Sources.RenderableSource value) {
        if (sourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSourceIsMutable();
          source_.add(value);
          onChanged();
        } else {
          sourceBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
       */
      public Builder addSource(
          int index, core.api.proto.Sources.RenderableSource value) {
        if (sourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSourceIsMutable();
          source_.add(index, value);
          onChanged();
        } else {
          sourceBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
       */
      public Builder addSource(
          core.api.proto.Sources.RenderableSource.Builder builderForValue) {
        if (sourceBuilder_ == null) {
          ensureSourceIsMutable();
          source_.add(builderForValue.build());
          onChanged();
        } else {
          sourceBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
       */
      public Builder addSource(
          int index, core.api.proto.Sources.RenderableSource.Builder builderForValue) {
        if (sourceBuilder_ == null) {
          ensureSourceIsMutable();
          source_.add(index, builderForValue.build());
          onChanged();
        } else {
          sourceBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
       */
      public Builder addAllSource(
          java.lang.Iterable<? extends core.api.proto.Sources.RenderableSource> values) {
        if (sourceBuilder_ == null) {
          ensureSourceIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, source_);
          onChanged();
        } else {
          sourceBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
       */
      public Builder clearSource() {
        if (sourceBuilder_ == null) {
          source_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          sourceBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
       */
      public Builder removeSource(int index) {
        if (sourceBuilder_ == null) {
          ensureSourceIsMutable();
          source_.remove(index);
          onChanged();
        } else {
          sourceBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
       */
      public core.api.proto.Sources.RenderableSource.Builder getSourceBuilder(
          int index) {
        return getSourceFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
       */
      public core.api.proto.Sources.RenderableSourceOrBuilder getSourceOrBuilder(
          int index) {
        if (sourceBuilder_ == null) {
          return source_.get(index);  } else {
          return sourceBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
       */
      public java.util.List<? extends core.api.proto.Sources.RenderableSourceOrBuilder> 
           getSourceOrBuilderList() {
        if (sourceBuilder_ != null) {
          return sourceBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(source_);
        }
      }
      /**
       * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
       */
      public core.api.proto.Sources.RenderableSource.Builder addSourceBuilder() {
        return getSourceFieldBuilder().addBuilder(
            core.api.proto.Sources.RenderableSource.getDefaultInstance());
      }
      /**
       * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
       */
      public core.api.proto.Sources.RenderableSource.Builder addSourceBuilder(
          int index) {
        return getSourceFieldBuilder().addBuilder(
            index, core.api.proto.Sources.RenderableSource.getDefaultInstance());
      }
      /**
       * <code>repeated .core.api.proto.RenderableSource source = 1;</code>
       */
      public java.util.List<core.api.proto.Sources.RenderableSource.Builder> 
           getSourceBuilderList() {
        return getSourceFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          core.api.proto.Sources.RenderableSource, core.api.proto.Sources.RenderableSource.Builder, core.api.proto.Sources.RenderableSourceOrBuilder> 
          getSourceFieldBuilder() {
        if (sourceBuilder_ == null) {
          sourceBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              core.api.proto.Sources.RenderableSource, core.api.proto.Sources.RenderableSource.Builder, core.api.proto.Sources.RenderableSourceOrBuilder>(
                  source_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          source_ = null;
        }
        return sourceBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:core.api.proto.ListSourceResponse)
    }

    // @@protoc_insertion_point(class_scope:core.api.proto.ListSourceResponse)
    private static final core.api.proto.Sources.ListSourceResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new core.api.proto.Sources.ListSourceResponse();
    }

    public static core.api.proto.Sources.ListSourceResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ListSourceResponse>
        PARSER = new com.google.protobuf.AbstractParser<ListSourceResponse>() {
      @java.lang.Override
      public ListSourceResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ListSourceResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListSourceResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public core.api.proto.Sources.ListSourceResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RenderableSourceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:core.api.proto.RenderableSource)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string source_name = 1;</code>
     * @return Whether the sourceName field is set.
     */
    boolean hasSourceName();
    /**
     * <code>optional string source_name = 1;</code>
     * @return The sourceName.
     */
    java.lang.String getSourceName();
    /**
     * <code>optional string source_name = 1;</code>
     * @return The bytes for sourceName.
     */
    com.google.protobuf.ByteString
        getSourceNameBytes();

    /**
     * <code>optional string source_icon_url = 2;</code>
     * @return Whether the sourceIconUrl field is set.
     */
    boolean hasSourceIconUrl();
    /**
     * <code>optional string source_icon_url = 2;</code>
     * @return The sourceIconUrl.
     */
    java.lang.String getSourceIconUrl();
    /**
     * <code>optional string source_icon_url = 2;</code>
     * @return The bytes for sourceIconUrl.
     */
    com.google.protobuf.ByteString
        getSourceIconUrlBytes();
  }
  /**
   * Protobuf type {@code core.api.proto.RenderableSource}
   */
  public static final class RenderableSource extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:core.api.proto.RenderableSource)
      RenderableSourceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RenderableSource.newBuilder() to construct.
    private RenderableSource(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RenderableSource() {
      sourceName_ = "";
      sourceIconUrl_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RenderableSource();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return core.api.proto.Sources.internal_static_core_api_proto_RenderableSource_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return core.api.proto.Sources.internal_static_core_api_proto_RenderableSource_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              core.api.proto.Sources.RenderableSource.class, core.api.proto.Sources.RenderableSource.Builder.class);
    }

    private int bitField0_;
    public static final int SOURCE_NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sourceName_ = "";
    /**
     * <code>optional string source_name = 1;</code>
     * @return Whether the sourceName field is set.
     */
    @java.lang.Override
    public boolean hasSourceName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string source_name = 1;</code>
     * @return The sourceName.
     */
    @java.lang.Override
    public java.lang.String getSourceName() {
      java.lang.Object ref = sourceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sourceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string source_name = 1;</code>
     * @return The bytes for sourceName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourceNameBytes() {
      java.lang.Object ref = sourceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCE_ICON_URL_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sourceIconUrl_ = "";
    /**
     * <code>optional string source_icon_url = 2;</code>
     * @return Whether the sourceIconUrl field is set.
     */
    @java.lang.Override
    public boolean hasSourceIconUrl() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string source_icon_url = 2;</code>
     * @return The sourceIconUrl.
     */
    @java.lang.Override
    public java.lang.String getSourceIconUrl() {
      java.lang.Object ref = sourceIconUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sourceIconUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string source_icon_url = 2;</code>
     * @return The bytes for sourceIconUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourceIconUrlBytes() {
      java.lang.Object ref = sourceIconUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceIconUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sourceName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sourceIconUrl_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sourceName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sourceIconUrl_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof core.api.proto.Sources.RenderableSource)) {
        return super.equals(obj);
      }
      core.api.proto.Sources.RenderableSource other = (core.api.proto.Sources.RenderableSource) obj;

      if (hasSourceName() != other.hasSourceName()) return false;
      if (hasSourceName()) {
        if (!getSourceName()
            .equals(other.getSourceName())) return false;
      }
      if (hasSourceIconUrl() != other.hasSourceIconUrl()) return false;
      if (hasSourceIconUrl()) {
        if (!getSourceIconUrl()
            .equals(other.getSourceIconUrl())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSourceName()) {
        hash = (37 * hash) + SOURCE_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getSourceName().hashCode();
      }
      if (hasSourceIconUrl()) {
        hash = (37 * hash) + SOURCE_ICON_URL_FIELD_NUMBER;
        hash = (53 * hash) + getSourceIconUrl().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static core.api.proto.Sources.RenderableSource parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.Sources.RenderableSource parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.Sources.RenderableSource parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.Sources.RenderableSource parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.Sources.RenderableSource parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static core.api.proto.Sources.RenderableSource parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static core.api.proto.Sources.RenderableSource parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static core.api.proto.Sources.RenderableSource parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static core.api.proto.Sources.RenderableSource parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static core.api.proto.Sources.RenderableSource parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static core.api.proto.Sources.RenderableSource parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static core.api.proto.Sources.RenderableSource parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(core.api.proto.Sources.RenderableSource prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code core.api.proto.RenderableSource}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:core.api.proto.RenderableSource)
        core.api.proto.Sources.RenderableSourceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return core.api.proto.Sources.internal_static_core_api_proto_RenderableSource_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return core.api.proto.Sources.internal_static_core_api_proto_RenderableSource_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                core.api.proto.Sources.RenderableSource.class, core.api.proto.Sources.RenderableSource.Builder.class);
      }

      // Construct using core.api.proto.Sources.RenderableSource.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        sourceName_ = "";
        sourceIconUrl_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return core.api.proto.Sources.internal_static_core_api_proto_RenderableSource_descriptor;
      }

      @java.lang.Override
      public core.api.proto.Sources.RenderableSource getDefaultInstanceForType() {
        return core.api.proto.Sources.RenderableSource.getDefaultInstance();
      }

      @java.lang.Override
      public core.api.proto.Sources.RenderableSource build() {
        core.api.proto.Sources.RenderableSource result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public core.api.proto.Sources.RenderableSource buildPartial() {
        core.api.proto.Sources.RenderableSource result = new core.api.proto.Sources.RenderableSource(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(core.api.proto.Sources.RenderableSource result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.sourceName_ = sourceName_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sourceIconUrl_ = sourceIconUrl_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof core.api.proto.Sources.RenderableSource) {
          return mergeFrom((core.api.proto.Sources.RenderableSource)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(core.api.proto.Sources.RenderableSource other) {
        if (other == core.api.proto.Sources.RenderableSource.getDefaultInstance()) return this;
        if (other.hasSourceName()) {
          sourceName_ = other.sourceName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasSourceIconUrl()) {
          sourceIconUrl_ = other.sourceIconUrl_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                sourceName_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                sourceIconUrl_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object sourceName_ = "";
      /**
       * <code>optional string source_name = 1;</code>
       * @return Whether the sourceName field is set.
       */
      public boolean hasSourceName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string source_name = 1;</code>
       * @return The sourceName.
       */
      public java.lang.String getSourceName() {
        java.lang.Object ref = sourceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sourceName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string source_name = 1;</code>
       * @return The bytes for sourceName.
       */
      public com.google.protobuf.ByteString
          getSourceNameBytes() {
        java.lang.Object ref = sourceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string source_name = 1;</code>
       * @param value The sourceName to set.
       * @return This builder for chaining.
       */
      public Builder setSourceName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sourceName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string source_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSourceName() {
        sourceName_ = getDefaultInstance().getSourceName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string source_name = 1;</code>
       * @param value The bytes for sourceName to set.
       * @return This builder for chaining.
       */
      public Builder setSourceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        sourceName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object sourceIconUrl_ = "";
      /**
       * <code>optional string source_icon_url = 2;</code>
       * @return Whether the sourceIconUrl field is set.
       */
      public boolean hasSourceIconUrl() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string source_icon_url = 2;</code>
       * @return The sourceIconUrl.
       */
      public java.lang.String getSourceIconUrl() {
        java.lang.Object ref = sourceIconUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sourceIconUrl_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string source_icon_url = 2;</code>
       * @return The bytes for sourceIconUrl.
       */
      public com.google.protobuf.ByteString
          getSourceIconUrlBytes() {
        java.lang.Object ref = sourceIconUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceIconUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string source_icon_url = 2;</code>
       * @param value The sourceIconUrl to set.
       * @return This builder for chaining.
       */
      public Builder setSourceIconUrl(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sourceIconUrl_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string source_icon_url = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSourceIconUrl() {
        sourceIconUrl_ = getDefaultInstance().getSourceIconUrl();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string source_icon_url = 2;</code>
       * @param value The bytes for sourceIconUrl to set.
       * @return This builder for chaining.
       */
      public Builder setSourceIconUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        sourceIconUrl_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:core.api.proto.RenderableSource)
    }

    // @@protoc_insertion_point(class_scope:core.api.proto.RenderableSource)
    private static final core.api.proto.Sources.RenderableSource DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new core.api.proto.Sources.RenderableSource();
    }

    public static core.api.proto.Sources.RenderableSource getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RenderableSource>
        PARSER = new com.google.protobuf.AbstractParser<RenderableSource>() {
      @java.lang.Override
      public RenderableSource parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RenderableSource> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RenderableSource> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public core.api.proto.Sources.RenderableSource getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_api_proto_ListSourceRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_api_proto_ListSourceRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_api_proto_ListSourceResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_api_proto_ListSourceResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_api_proto_RenderableSource_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_api_proto_RenderableSource_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rsources.proto\022\016core.api.proto\"\023\n\021ListS" +
      "ourceRequest\"F\n\022ListSourceResponse\0220\n\006so" +
      "urce\030\001 \003(\0132 .core.api.proto.RenderableSo" +
      "urce\"@\n\020RenderableSource\022\023\n\013source_name\030" +
      "\001 \001(\t\022\027\n\017source_icon_url\030\002 \001(\t2h\n\016Source" +
      "Registry\022V\n\013ListSources\022!.core.api.proto" +
      ".ListSourceRequest\032\".core.api.proto.List" +
      "SourceResponse\"\000B\tH\003\242\002\004SUIP"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_core_api_proto_ListSourceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_core_api_proto_ListSourceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_api_proto_ListSourceRequest_descriptor,
        new java.lang.String[] { });
    internal_static_core_api_proto_ListSourceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_core_api_proto_ListSourceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_api_proto_ListSourceResponse_descriptor,
        new java.lang.String[] { "Source", });
    internal_static_core_api_proto_RenderableSource_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_core_api_proto_RenderableSource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_api_proto_RenderableSource_descriptor,
        new java.lang.String[] { "SourceName", "SourceIconUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
