// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: concern_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_concern_5fservice_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_concern_5fservice_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4022000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4022000 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_concern_5fservice_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_concern_5fservice_2eproto {
  static const ::uint32_t offsets[];
};
namespace core {
namespace api {
namespace proto {
class GetConcernRequest;
struct GetConcernRequestDefaultTypeInternal;
extern GetConcernRequestDefaultTypeInternal _GetConcernRequest_default_instance_;
class GetConcernResponse;
struct GetConcernResponseDefaultTypeInternal;
extern GetConcernResponseDefaultTypeInternal _GetConcernResponse_default_instance_;
class RenderableConcern;
struct RenderableConcernDefaultTypeInternal;
extern RenderableConcernDefaultTypeInternal _RenderableConcern_default_instance_;
}  // namespace proto
}  // namespace api
}  // namespace core
PROTOBUF_NAMESPACE_OPEN
template <>
::core::api::proto::GetConcernRequest* Arena::CreateMaybeMessage<::core::api::proto::GetConcernRequest>(Arena*);
template <>
::core::api::proto::GetConcernResponse* Arena::CreateMaybeMessage<::core::api::proto::GetConcernResponse>(Arena*);
template <>
::core::api::proto::RenderableConcern* Arena::CreateMaybeMessage<::core::api::proto::RenderableConcern>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace core {
namespace api {
namespace proto {
enum GetConcernStatus : int {
  GET_CONCERN_STATUS_UNKNOWN = 0,
  GET_CONCERN_STATUS_OK = 1,
  GET_CONCERN_STATUS_CONCERN_NOT_FOUND = 2,
};

bool GetConcernStatus_IsValid(int value);
constexpr GetConcernStatus GetConcernStatus_MIN = static_cast<GetConcernStatus>(0);
constexpr GetConcernStatus GetConcernStatus_MAX = static_cast<GetConcernStatus>(2);
constexpr int GetConcernStatus_ARRAYSIZE = 2 + 1;
const std::string& GetConcernStatus_Name(GetConcernStatus value);
template <typename T>
const std::string& GetConcernStatus_Name(T value) {
  static_assert(std::is_same<T, GetConcernStatus>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to GetConcernStatus_Name().");
  return GetConcernStatus_Name(static_cast<GetConcernStatus>(value));
}
const std::string& GetConcernStatus_Name(GetConcernStatus value);
bool GetConcernStatus_Parse(absl::string_view name, GetConcernStatus* value);

// ===================================================================


// -------------------------------------------------------------------

class RenderableConcern final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:core.api.proto.RenderableConcern) */ {
 public:
  inline RenderableConcern() : RenderableConcern(nullptr) {}
  ~RenderableConcern() override;
  explicit PROTOBUF_CONSTEXPR RenderableConcern(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RenderableConcern(const RenderableConcern& from);
  RenderableConcern(RenderableConcern&& from) noexcept
    : RenderableConcern() {
    *this = ::std::move(from);
  }

  inline RenderableConcern& operator=(const RenderableConcern& from) {
    CopyFrom(from);
    return *this;
  }
  inline RenderableConcern& operator=(RenderableConcern&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const RenderableConcern& default_instance() {
    return *internal_default_instance();
  }
  static inline const RenderableConcern* internal_default_instance() {
    return reinterpret_cast<const RenderableConcern*>(
               &_RenderableConcern_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RenderableConcern& a, RenderableConcern& b) {
    a.Swap(&b);
  }
  inline void Swap(RenderableConcern* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RenderableConcern* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RenderableConcern* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RenderableConcern>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const RenderableConcern& from);
  void MergeFrom(const RenderableConcern& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RenderableConcern* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "core.api.proto.RenderableConcern";
  }
  protected:
  explicit RenderableConcern(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kConcernIdFieldNumber = 1,
  };
  // optional uint64 concern_id = 1;
  bool has_concern_id() const;
  void clear_concern_id() ;
  ::uint64_t concern_id() const;
  void set_concern_id(::uint64_t value);

  private:
  ::uint64_t _internal_concern_id() const;
  void _internal_set_concern_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:core.api.proto.RenderableConcern)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::uint64_t concern_id_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_concern_5fservice_2eproto;
};// -------------------------------------------------------------------

class GetConcernRequest final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:core.api.proto.GetConcernRequest) */ {
 public:
  inline GetConcernRequest() : GetConcernRequest(nullptr) {}
  ~GetConcernRequest() override;
  explicit PROTOBUF_CONSTEXPR GetConcernRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetConcernRequest(const GetConcernRequest& from);
  GetConcernRequest(GetConcernRequest&& from) noexcept
    : GetConcernRequest() {
    *this = ::std::move(from);
  }

  inline GetConcernRequest& operator=(const GetConcernRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetConcernRequest& operator=(GetConcernRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const GetConcernRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetConcernRequest* internal_default_instance() {
    return reinterpret_cast<const GetConcernRequest*>(
               &_GetConcernRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GetConcernRequest& a, GetConcernRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetConcernRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetConcernRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetConcernRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetConcernRequest>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const GetConcernRequest& from);
  void MergeFrom(const GetConcernRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetConcernRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "core.api.proto.GetConcernRequest";
  }
  protected:
  explicit GetConcernRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kConcernIdFieldNumber = 1,
  };
  // optional uint64 concern_id = 1;
  bool has_concern_id() const;
  void clear_concern_id() ;
  ::uint64_t concern_id() const;
  void set_concern_id(::uint64_t value);

  private:
  ::uint64_t _internal_concern_id() const;
  void _internal_set_concern_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:core.api.proto.GetConcernRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::uint64_t concern_id_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_concern_5fservice_2eproto;
};// -------------------------------------------------------------------

class GetConcernResponse final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:core.api.proto.GetConcernResponse) */ {
 public:
  inline GetConcernResponse() : GetConcernResponse(nullptr) {}
  ~GetConcernResponse() override;
  explicit PROTOBUF_CONSTEXPR GetConcernResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetConcernResponse(const GetConcernResponse& from);
  GetConcernResponse(GetConcernResponse&& from) noexcept
    : GetConcernResponse() {
    *this = ::std::move(from);
  }

  inline GetConcernResponse& operator=(const GetConcernResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetConcernResponse& operator=(GetConcernResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const GetConcernResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetConcernResponse* internal_default_instance() {
    return reinterpret_cast<const GetConcernResponse*>(
               &_GetConcernResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetConcernResponse& a, GetConcernResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetConcernResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetConcernResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetConcernResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetConcernResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const GetConcernResponse& from);
  void MergeFrom(const GetConcernResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetConcernResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "core.api.proto.GetConcernResponse";
  }
  protected:
  explicit GetConcernResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kConcernFieldNumber = 1,
    kStatusFieldNumber = 2,
  };
  // optional .core.api.proto.RenderableConcern concern = 1;
  bool has_concern() const;
  void clear_concern() ;
  const ::core::api::proto::RenderableConcern& concern() const;
  PROTOBUF_NODISCARD ::core::api::proto::RenderableConcern* release_concern();
  ::core::api::proto::RenderableConcern* mutable_concern();
  void set_allocated_concern(::core::api::proto::RenderableConcern* concern);
  private:
  const ::core::api::proto::RenderableConcern& _internal_concern() const;
  ::core::api::proto::RenderableConcern* _internal_mutable_concern();
  public:
  void unsafe_arena_set_allocated_concern(
      ::core::api::proto::RenderableConcern* concern);
  ::core::api::proto::RenderableConcern* unsafe_arena_release_concern();
  // optional .core.api.proto.GetConcernStatus status = 2;
  bool has_status() const;
  void clear_status() ;
  ::core::api::proto::GetConcernStatus status() const;
  void set_status(::core::api::proto::GetConcernStatus value);

  private:
  ::core::api::proto::GetConcernStatus _internal_status() const;
  void _internal_set_status(::core::api::proto::GetConcernStatus value);

  public:
  // @@protoc_insertion_point(class_scope:core.api.proto.GetConcernResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::core::api::proto::RenderableConcern* concern_;
    int status_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_concern_5fservice_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RenderableConcern

// optional uint64 concern_id = 1;
inline bool RenderableConcern::has_concern_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void RenderableConcern::clear_concern_id() {
  _impl_.concern_id_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint64_t RenderableConcern::concern_id() const {
  // @@protoc_insertion_point(field_get:core.api.proto.RenderableConcern.concern_id)
  return _internal_concern_id();
}
inline void RenderableConcern::set_concern_id(::uint64_t value) {
  _internal_set_concern_id(value);
  // @@protoc_insertion_point(field_set:core.api.proto.RenderableConcern.concern_id)
}
inline ::uint64_t RenderableConcern::_internal_concern_id() const {
  return _impl_.concern_id_;
}
inline void RenderableConcern::_internal_set_concern_id(::uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.concern_id_ = value;
}

// -------------------------------------------------------------------

// GetConcernRequest

// optional uint64 concern_id = 1;
inline bool GetConcernRequest::has_concern_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void GetConcernRequest::clear_concern_id() {
  _impl_.concern_id_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint64_t GetConcernRequest::concern_id() const {
  // @@protoc_insertion_point(field_get:core.api.proto.GetConcernRequest.concern_id)
  return _internal_concern_id();
}
inline void GetConcernRequest::set_concern_id(::uint64_t value) {
  _internal_set_concern_id(value);
  // @@protoc_insertion_point(field_set:core.api.proto.GetConcernRequest.concern_id)
}
inline ::uint64_t GetConcernRequest::_internal_concern_id() const {
  return _impl_.concern_id_;
}
inline void GetConcernRequest::_internal_set_concern_id(::uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.concern_id_ = value;
}

// -------------------------------------------------------------------

// GetConcernResponse

// optional .core.api.proto.RenderableConcern concern = 1;
inline bool GetConcernResponse::has_concern() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.concern_ != nullptr);
  return value;
}
inline void GetConcernResponse::clear_concern() {
  if (_impl_.concern_ != nullptr) _impl_.concern_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::core::api::proto::RenderableConcern& GetConcernResponse::_internal_concern() const {
  const ::core::api::proto::RenderableConcern* p = _impl_.concern_;
  return p != nullptr ? *p : reinterpret_cast<const ::core::api::proto::RenderableConcern&>(
      ::core::api::proto::_RenderableConcern_default_instance_);
}
inline const ::core::api::proto::RenderableConcern& GetConcernResponse::concern() const {
  // @@protoc_insertion_point(field_get:core.api.proto.GetConcernResponse.concern)
  return _internal_concern();
}
inline void GetConcernResponse::unsafe_arena_set_allocated_concern(
    ::core::api::proto::RenderableConcern* concern) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.concern_);
  }
  _impl_.concern_ = concern;
  if (concern) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:core.api.proto.GetConcernResponse.concern)
}
inline ::core::api::proto::RenderableConcern* GetConcernResponse::release_concern() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::core::api::proto::RenderableConcern* temp = _impl_.concern_;
  _impl_.concern_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::core::api::proto::RenderableConcern* GetConcernResponse::unsafe_arena_release_concern() {
  // @@protoc_insertion_point(field_release:core.api.proto.GetConcernResponse.concern)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::core::api::proto::RenderableConcern* temp = _impl_.concern_;
  _impl_.concern_ = nullptr;
  return temp;
}
inline ::core::api::proto::RenderableConcern* GetConcernResponse::_internal_mutable_concern() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.concern_ == nullptr) {
    auto* p = CreateMaybeMessage<::core::api::proto::RenderableConcern>(GetArenaForAllocation());
    _impl_.concern_ = p;
  }
  return _impl_.concern_;
}
inline ::core::api::proto::RenderableConcern* GetConcernResponse::mutable_concern() {
  ::core::api::proto::RenderableConcern* _msg = _internal_mutable_concern();
  // @@protoc_insertion_point(field_mutable:core.api.proto.GetConcernResponse.concern)
  return _msg;
}
inline void GetConcernResponse::set_allocated_concern(::core::api::proto::RenderableConcern* concern) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.concern_;
  }
  if (concern) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(concern);
    if (message_arena != submessage_arena) {
      concern = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, concern, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.concern_ = concern;
  // @@protoc_insertion_point(field_set_allocated:core.api.proto.GetConcernResponse.concern)
}

// optional .core.api.proto.GetConcernStatus status = 2;
inline bool GetConcernResponse::has_status() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void GetConcernResponse::clear_status() {
  _impl_.status_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::core::api::proto::GetConcernStatus GetConcernResponse::status() const {
  // @@protoc_insertion_point(field_get:core.api.proto.GetConcernResponse.status)
  return _internal_status();
}
inline void GetConcernResponse::set_status(::core::api::proto::GetConcernStatus value) {
   _internal_set_status(value);
  // @@protoc_insertion_point(field_set:core.api.proto.GetConcernResponse.status)
}
inline ::core::api::proto::GetConcernStatus GetConcernResponse::_internal_status() const {
  return static_cast<::core::api::proto::GetConcernStatus>(_impl_.status_);
}
inline void GetConcernResponse::_internal_set_status(::core::api::proto::GetConcernStatus value) {
  assert(::core::api::proto::GetConcernStatus_IsValid(value));
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.status_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace api
}  // namespace core


PROTOBUF_NAMESPACE_OPEN

template <>
struct is_proto_enum<::core::api::proto::GetConcernStatus> : std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_concern_5fservice_2eproto_2epb_2eh
