// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from local_interface.djinni

package my.package.core;

import com.snapchat.djinni.NativeObjectManager;
import core.api.proto.ConcernService.RenderableConcern;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class ConcernService {
    public abstract RenderableConcern getConcern(long concernId);

    public static native ConcernService create();

    public static final class CppProxy extends ConcernService
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);

        @Override
        public RenderableConcern getConcern(long concernId)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getConcern(this.nativeRef, concernId);
        }
        private native RenderableConcern native_getConcern(long _nativeRef, long concernId);
    }
}
